import { BookContent } from './types';

const content: BookContent = {
  bookId: 5,
  keyPoints: [
    { text: 'Aufgrund längerer Trockenphasen und höheren Temperaturen im Sommer steigt die Waldbrandgefahr. Weitere Faktoren (Trockenschäden, geschwächte Bäume, Streu auf dem Waldboden das schnell austrocknet und entzundlich ist sowie lichte Kronen) verschärfen das Risiko. [2]', pages: [], chapters: [] },
    { text: 'Der Klimawandel verändert die Berechnungsgrundlage für die Belastung von Infrastruktur hinsichtlich der Häufigkeit von Hochwasserereignissen und dem Bedarf an Überschwemmungsgebieten. [2]', pages: [], chapters: [] },
    { text: 'Wetterextreme, darunter Starkregen, Hochwasser, Stürme, Dürren und Hitze werden häufiger und heftiger und sind keine Jahrhundertereignisse mehr sondern Teil der Realität auf die sich der Mensch einstellen muss. [6]', pages: [], chapters: [] },
    { text: 'Waldbrände bedeuten für den Menschen Lebens- und Gesunheitsgefahr (Todesfälle durch Flächenbrände, Luftverschmutzung durch Rußpartikel) und senken die Lebensqualität. [20]', pages: [], chapters: [] },
    { text: 'Der Anteil geschädigter einheimischer Bäume wird sich aufgrund von Trockenheit, steigenden Temperaturen und sinkender Grundwasserpegel jährlich erhöhen, während die Produktivität der Vegeation sinkt und die Anpassungsgrenze einiger Arten überschritten wird. [9]', pages: [], chapters: [] },
  ],
  sections: [
    {
      title: 'ZUR WELT IN DER SCHWAMM',
      bullets: [
        { text: 'Aufgrund mangelnder Resilienz gegenüber Trockenheit und Hitze kommte es zu einem zunehmenden Waldsterben. Der Verlust des Waldes als lebender Wasserspeicher verschäft die Wasserknappheit und sorgt außerdem für eine erhöhte Waldbrandgefahr. [1]', pages: [], chapters: [] },
        { text: 'Allgemein ist ein Anstieg der Waldbrandgefahr aufgrund wärmerer Sommer und längeren Trockenphasen zu verzeichnen. [2]', pages: [], chapters: [] },
        { text: 'Die Waldbrandgefahr wird durch Trockenschäden, geschwächte Bäume, mehr Streu auf dem Boden und lichtere Baumkronen erhöht. [2]', pages: [], chapters: [] },
        { text: 'Für Menschen bedeuten Waldbrände Lebensgefahr (als Todesopfer von Flächenbränden oder durch Luftverschmutzung) und eine Verschlechterung der Lebensqualität aufgrund von Rußpartikeln in der Luft. [1]', pages: [], chapters: [] },
        { text: 'Sturzfluten aufgrund häufigerer und stärkerer Niederschläge in Kombination mit einer zunehmenden Urbanisierung, können zukünftig vermehrt und intensiver auftreten. [3]', pages: [], chapters: [] },
        { text: 'Extremer Niederschlag wie der, der bereits Fluten in Bayern und Baden-Württemberg verursacht hat, wird durch den Klimawandel wahrscheinlicher und intensiver. [4]', pages: [], chapters: [] },
        { text: 'Der Klimawandel verändert die Berechnungsgrundlage für die Belastung von Infrastruktur hinsichtlich der Häufigkeit von Hochwasserereignissen und dem Bedarf an Überschwemmungsgebieten. [2]', pages: [], chapters: [] },
        { text: 'Häufigere Wetterextreme wirken sich auf die Hochwasserschutz-Infrastruktur sowie die sichere Trinkwasserversorgung aus und könnten Belastungen zukünftigen verschärfen. [5]', pages: [], chapters: [] },
        { text: 'Überschwemmungen und Fluten wirken sich negativ auf die physische (Verletzungen, ggf. tödlich) und psychische (Angstzustände, Depressionen, posttraumatische Belastungsstörung) menschliche Gesundheit aus. [1]', pages: [], chapters: [] },
        { text: 'Die Gefahr durch derartige Ereignisse die medizinische Versorgung hinsichtlich Personal und Infrastruktur nicht mehr gewährleisten zu können, verstärkt die Problematik weiter. [1]', pages: [], chapters: [] },
        { text: 'Wetterextreme, darunter Starkregen, Hochwasser, Stürme, Dürren und Hitze werden häufiger und heftiger und sind keine Jahrhundertereignisse mehr sondern Teil der Realität. [6]', pages: [], chapters: [] },
        { text: 'Laut der Europäischen Umweltagentur verursachten wetter- und klimabedingte Extremereignise in den EU-Mitgliedstaaten zwischen 1980 und 2021 wirtschaftliche Verluste in HÖhe von schätzungsweise 560 Mrd. €, davon 56,6 Mrd € im Jahr 2021. [7]', pages: [], chapters: [] },
      ],
    },
    {
      title: 'EXTREMWETTER',
      bullets: [
        { text: 'Wetterextreme, darunter Starkregen, Hochwasser, Stürme, Dürren und Hitze werden häufiger und heftiger und sind keine Jahrhundertereignisse mehr sondern Teil der Realität auf die sich der Mensch einstellen muss. [6]', pages: [15, 16, 22, 27], chapters: [1, 2] },
        { text: 'Häufiger auftretende Starkniederschläge erhöhen in Kombination mit einer zunehmenden durch Urbanisierung bedingten Flächenversiegelung das Auftreten sowie die Intensität von Sturzfluten. Vulnerabel sind insbesondere Gebiete mit schlechten oder unzureichenden natürlichen oder künstlichen Abflüssen. [8]', pages: [37], chapters: [3] },
        { text: 'Der Klimawandel verändert die Berechnungsgrundlage für die Belastung von Infrastruktur hinsichtlich der Häufigkeit von Hochwasserereignissen und dem Bedarf an Überschwemmungsgebieten. [2]', pages: [26], chapters: [2] },
        { text: 'Aufgrund längerer Trockenphasen und höheren Temperaturen im Sommer steigt die Waldbrandgefahr. Weitere Faktoren (Trockenschäden, geschwächte Bäume, Streu auf dem Waldboden das schnell austrocknet und entzundlich ist sowie lichte Kronen) verschärfen das Risiko. [2]', pages: [56, 57], chapters: [5] },
        { text: 'Dürren und Trockenheit in Kombination mit fehlenden Niederschlägen und Wassermangel erhöhen die Wahrscheinlichkeit von Steppen- und Waldbränden sowie Ernteausfällen enorm. [6][9]', pages: [62], chapters: [5] },
        { text: 'Waldbrände bedeuten für den Menschen Lebens- und Gesunheitsgefahr (Todesfälle durch Flächenbrände, Luftverschmutzung durch Rußpartikel) und senken die Lebensqualität. [20]', pages: [7, 63], chapters: [1, 5] },
        { text: 'Der aktuelle Wissensstand lässt vermuten, dass Dürren und Trockenheit in Zukunft länger anhaltend und häufiger werden. [10]', pages: [94], chapters: [8] },
        { text: 'Wetterextreme wie längere Dürreperioden und stärkere Niederschläge werden für die Zukunft erwartet. [11]', pages: [92], chapters: [8] },
      ],
    },
    {
      title: 'WASSERKNAPPHEIT',
      bullets: [
        { text: 'Das Wasser in Deutschland knapp ist, zeigt sich darin, dass in jedem zweiten Landkreis Wassedrstress herrscht. [12]', pages: [4], chapters: [1] },
        { text: 'Besonders betroffen sind Regionen mit viel Landwirtschaft und Industrie sowie einer hohen Bevölkerungsdichte. [12]', pages: [4], chapters: [1] },
        { text: 'Die zukünftige Wasserverfügbarkeit sinkt die Deutschland aufgrund des Klimawandels. Insbesondere während Trockenperioden kann es zu Engpässen in der Wasserverfügbarkeit kommen wodurch Nutzungskonflikte entstehen oder verschärft werden. [13]', pages: [4], chapters: [1] },
        { text: 'In Folge einer extremen Dürre in Südafrika ab 2015 und dem damit verbundenen Rückgang des Wasserpegels in einer Talsperre die zur Trinkwasserversorgung genutzt wird, wurden Sparmaßnahmen umgesetzt, die den täglichen pro-Kopf- Wasserverbrauch zeitweise auf 50 Liter begrenzten. [5]', pages: [4], chapters: [1] },
        { text: 'Wasser ist ein knappes, begehrtes und sehr ungleich verteiltes Gut. [14]', pages: [8], chapters: [1] },
        { text: 'Etwa 2,2 Mrd. Menschen, insbesondere in Ländern mit mittleren und niedriegen Einkommensverhältnissen, haben heutzutage keinen sicheren Zugang zu sauberem Trinkwasser. [15]', pages: [49], chapters: [4] },
        { text: 'Neben der Vitalität des Individuums wird auch die Leistung der Gesellschaft durch unregelmäßige oder unzureichende Wasserversorgung beeinträchtigt, was sowohl wirtschaftliche als auch gesellschaftspolitische Konsequenzen hat. [16]', pages: [72], chapters: [6] },
        { text: 'Lange andauernde Dürreperioden verändern die Bodenfeuchte und führen zum versiegen von oberflächennahen Quellwasserverschüttungen sowie einem Absinken des Grundwasserpegels. [5]', pages: [64], chapters: [5] },
        { text: 'Neue Technologien, Digitalisierung und KI werden einen großen Einfluss auf den Wasserverbrauch in der Zukunft haben. [26]', pages: [11, 21, 41], chapters: [1, 2, 3] },
        { text: 'Da moderne Probleme moderne Lösungen erfordern, bieten neue Technologien das Potenzial, Wassermanagement zu revolutionieren und nachhaltiger zu gestalten. [27]', pages: [48], chapters: [4] },
      ],
    },
     {
      title: 'HITZE',
      bullets: [
        { text: 'In den letzten Jahrzehnten haben Hitzewellen zugenommen. [17]', pages: [14], chapters: [1] },
        { text: 'Für 2031-2060 wird bei ungebremstem Treibhausgasausstoß ein Anstieg von fünf bis zehn Heißen Tagen (ab 30°C) in Norddeutschland, und zehn bis zwanzig in Süddeutschland prognositiziert. [17]', pages: [14], chapters: [1] },
        { text: 'Das Städte eigene klimatische Bedingungen entwickeln liegt an der dichten Bebauung, der Versiegelung von Flächen, der Abwärme durch Verkehr und Gebäude sowie dem Mangel an Wasser- und Grünflächen. [2]', pages: [96], chapters: [5] },
        { text: 'Das Phänomen der städtischen Wärmeinseln ergibt sich aus diesen Faktoren und ist der Grund, weshalb urbane Regionen im vergleich zu ländlichen deutlich höhere Temperaturen aufweisen. [18]', pages: [31], chapters: [3] },
        { text: 'Mit 2,5°C erwärmt sich Deutschland doppelt so schnell wie der globale Durchschnitt. [19]', pages: [19, 16], chapters: [1, 2] },
      ],
    },
    {
      title: 'NATUR & BODEN',
      bullets: [
        { text: 'Der Anteil geschädigter einheimischer Bäume wird sich aufgrund von Trockenheit, steigenden Temperaturen und sinkender Grundwasserpegel jährlich erhöhen, während die Produktivität der Vegeation sinkt und die Anpassungsgrenze einiger Arten überschritten wird. [9]', pages: [8], chapters: [1] },
        { text: 'Aufgrund fehlerhafter Forstwirtschaft und mangelnder Resilienz gegenüber Trockenheit und Hitze kommt es zu einem Anstieg des Waldsterbens. Dadurch gehen auch die Wasserspeicher-Fähigkeiten des Waldes verloren. [1]', pages: [50, 51], chapters: [4] },
        { text: 'Das Resultat der globalen Erwärmung kann ein Übergang der Vegeation durch Austrocknen von Pflanzen oder dem Überschreiten derer Hitzetoleranzgrenzen in Richtung Trockenwälder, Steppen- und Wüstenbildung sein. [9]', pages: [3, 4, 8], chapters: [1] },
        { text: 'Die Bodenfeuchte wird sich mit jedem Grad der globalen Erwärmung stärker verändern und könnte sich in einigen Regionen (z.B. Westeuropa) um bis zu 40% verringern. [21]', pages: [50], chapters: [4] },
        { text: '47% der Landflächen sind jährlich von Dürre betroffen, ein Anstieg von 29% im Vergleich zu den Jahren 1951-1960. [1]', pages: [94], chapters: [8] },
        { text: 'Für das Pflanzenwachstum und das allgmeeine Funktionieren von Ökosystemen wie Wäldern oder Graslandschaften ist die Verfügbarkeit von Wasser entscheidend. Gleichzeitig sind derartige Ökosysteme für die stabilisierung der lokalen Süßwasserverfügbarkeit und -qualität wichtig. [16]', pages: [94, 95], chapters: [8] },
      ],
    },
    {
      title: 'URBANE ENTWICKLUNG',
      bullets: [
        { text: 'In Städten bedeutet Urbanisierung eine Verdichtung auf vielen Ebenen und ist geografische sowie infrastrukturelle Komponente mit einem hochkomplexen sozialen Gefüge. [22]', pages: [21], chapters: [2] },
        { text: 'Urbane Gebiete, inbesondere Regionen mit hoher Nachfrage, Wirtschaftsleistung oder Tourismus, sind am akutesten von Wohnungsengpässen betroffen. [23]', pages: [31], chapters: [3] },
        { text: 'Durch den Urbanisierungstrend kommt es zu regionalen Ungleichgewichten von Wohnraum. Während in einigen Regionen struktureller Mangel an Wohnraum herrscht, stehen in anderen Wohnungen leer. [24]', pages: [7], chapters: [1] },
        { text: 'Aktuell (Stand 2021) beträgt die durchschnittliche Wohnfläche pro Person in Deutschland etwa 47 m². Im Jahr 1950 lag dieser Wert noch bei 14 m². [24]', pages: [3], chapters: [1] },
        { text: 'Vor allem ältere Menschen mit einer Wohnfläche von mehr als 80 m² finden ihren Wohnraum zu groß. [24]', pages: [3], chapters: [1] },
      ],
    },
    {
      title: 'SOZIALE ISOLATION',
      bullets: [
        { text: 'Die Verbreitung von Einpersonenhaushalten entzieht den Menschen traditionelle Unterstützungsnetzwerke. [25]', pages: [78, 18, 86], chapters: [6, 2, 7] },
        { text: 'Auch das Aufkommen neuer Technologien kann Einsamkeit weiter verschärfen. [25]', pages: [14, 15, 79, 78, 18], chapters: [1, 6, 2] },
        { text: '. [2]', pages: [96], chapters: [5] },
      ],
    },
  ],
  sources: [
    { id: 1, text: 'Bassen, A. et al. (2024): "Hauptgutachten Wasser in einer aufgeheizten Welt", WBGU - Wissenschaftlicher Beirat der Bundesregierung Globale Umweltveränderungen. S. 93, verfügbar unter: https://www.wbgu.de/fileadmin/user_upload/wbgu/publikationen/hauptgutachten/hg2024/pdf/wbgu_hg2024.pdf' },
    { id: 2, text: 'DWD - Deutscher Wetterdienst (2025):"Was wir über das Extremwetter in Deutschland wissen: Stand der Wissenschaft zu Extremwetterereignissen im Klimawandel in Deutschland, Ausgabe 2025", DMG - Deutsche Meteorologische Gesellschaft. S. 18, verfügbar unter: https://www.dmg-ev.de/wp-content/uploads/2026/02/faktenpapier_extremwetterkongress.pdf' },
    { id: 3, text: 'Bassen, A. et al. (2024): "Hauptgutachten Wasser in einer aufgeheizten Welt", WBGU - Wissenschaftlicher Beirat der Bundesregierung Globale Umweltveränderungen. S. 73, verfügbar unter: https://www.wbgu.de/fileadmin/user_upload/wbgu/publikationen/hauptgutachten/hg2024/pdf/wbgu_hg2024.pdf' },
    { id: 4, text: 'BUND (2024): "Hochwasser: Extremwetterereignisse Symptom der Klimakrise", verfügbar unter: https://www.bund.net/service/presse/pressemitteilungen/detail/news/hochwasser-extremwetterereignisse-symptom-der-klimakrise/' },
    { id: 5, text: 'Bassen, A. et al. (2024): "Hauptgutachten Wasser in einer aufgeheizten Welt", WBGU - Wissenschaftlicher Beirat der Bundesregierung Globale Umweltveränderungen. S. 74-75, verfügbar unter: https://www.wbgu.de/fileadmin/user_upload/wbgu/publikationen/hauptgutachten/hg2024/pdf/wbgu_hg2024.pdf' },
    { id: 6, text: 'Bundesministerium für Umwelt, Klimaschutz, Naturschutz und nukleare Sicherheit (2025): "Die Deutsche Anpassungsstrategie an den Klimawandel", verfügbar unter: https://www.bundesumweltministerium.de/themen/klimaanpassung/die-deutsche-anpassungsstrategie-an-den-klimawandel' },
    { id: 7, text: 'Bassen, A. et al. (2024): "Hauptgutachten Wasser in einer aufgeheizten Welt", WBGU - Wissenschaftlicher Beirat der Bundesregierung Globale Umweltveränderungen. S. 83, verfügbar unter: https://www.wbgu.de/fileadmin/user_upload/wbgu/publikationen/hauptgutachten/hg2024/pdf/wbgu_hg2024.pdf' },
    { id: 8, text: 'Bassen, A. et al. (2024): "Hauptgutachten Wasser in einer aufgeheizten Welt", WBGU - Wissenschaftlicher Beirat der Bundesregierung Globale Umweltveränderungen. S. 36, 73, verfügbar unter: https://www.wbgu.de/fileadmin/user_upload/wbgu/publikationen/hauptgutachten/hg2024/pdf/wbgu_hg2024.pdf' },
    { id: 9, text: 'Bassen, A. et al. (2024): "Hauptgutachten Wasser in einer aufgeheizten Welt", WBGU - Wissenschaftlicher Beirat der Bundesregierung Globale Umweltveränderungen. S. 90, verfügbar unter: https://www.wbgu.de/fileadmin/user_upload/wbgu/publikationen/hauptgutachten/hg2024/pdf/wbgu_hg2024.pdf' },
    { id: 10, text: 'Stein, U. et al. (2024): "Auswirkungen des Klimawandels auf die Wasserverfügbarkeit - Anpassung an Trockenheit und Dürre in Deutschland (WADKlim)", Umweltbundesamt, 143/2024. S. 290, verfügbar unter: https://www.umweltbundesamt.de/system/files/medien/11850/publikationen/143_2024_texte_wadklim.pdf' },
    { id: 11, text: 'Wunsch, A., Liesch, T., Broda, S. (2022): "Deep learning shows declining groundwater levels in Germany until 2100 due to climate change", Nat Commun 13, 1221. S. 2, verfügbar unter: https://www.nature.com/articles/s41467-022-28770-2' },
    { id: 12, text: 'BUND (2025): "Grundwasser in Gefahr: BUND legt Studie zur Wasserknappheit vor", verfügbar unter: https://www.bund.net/themen/aktuelles/detail-aktuelles/news/grundwasser-in-gefahr-bund-legt-studie-zur-wasserknappheit-vor/' },
    { id: 13, text: 'Umweltbundesamt (2024): "Auswirkungen des Klimawandels auf die Wasserverfügbarkeit", verfügbar unter: https://www.umweltbundesamt.de/auswirkung-des-klimawandels-auf-die' },
    { id: 14, text: 'Bassen, A. et al. (2024): "Hauptgutachten Wasser in einer aufgeheizten Welt", WBGU - Wissenschaftlicher Beirat der Bundesregierung Globale Umweltveränderungen. S. 86, verfügbar unter: https://www.wbgu.de/fileadmin/user_upload/wbgu/publikationen/hauptgutachten/hg2024/pdf/wbgu_hg2024.pdf' },
    { id: 15, text: 'Bassen, A. et al. (2024): "Hauptgutachten Wasser in einer aufgeheizten Welt", WBGU - Wissenschaftlicher Beirat der Bundesregierung Globale Umweltveränderungen. S. 29, verfügbar unter: https://www.wbgu.de/fileadmin/user_upload/wbgu/publikationen/hauptgutachten/hg2024/pdf/wbgu_hg2024.pdf' },
    { id: 16, text: 'Bassen, A. et al. (2024): "Hauptgutachten Wasser in einer aufgeheizten Welt", WBGU - Wissenschaftlicher Beirat der Bundesregierung Globale Umweltveränderungen. S. 5, verfügbar unter: https://www.wbgu.de/fileadmin/user_upload/wbgu/publikationen/hauptgutachten/hg2024/pdf/wbgu_hg2024.pdf' },
    { id: 17, text: 'DWD - Deutscher Wetterdienst (2025):"Was wir über das Extremwetter in Deutschland wissen: Stand der Wissenschaft zu Extremwetterereignissen im Klimawandel in Deutschland, Ausgabe 2025", DMG - Deutsche Meteorologische Gesellschaft. S. 7, verfügbar unter: https://www.dmg-ev.de/wp-content/uploads/2026/02/faktenpapier_extremwetterkongress.pdf' },
    { id: 18, text: 'DWD - Deutscher Wetterdienst (2025):"Was wir über das Extremwetter in Deutschland wissen: Stand der Wissenschaft zu Extremwetterereignissen im Klimawandel in Deutschland, Ausgabe 2025", DMG - Deutsche Meteorologische Gesellschaft. S. 11, verfügbar unter: https://www.dmg-ev.de/wp-content/uploads/2026/02/faktenpapier_extremwetterkongress.pdf' },
    { id: 19, text: 'DWD - Deutscher Wetterdienst (2025):"Was wir über das Extremwetter in Deutschland wissen: Stand der Wissenschaft zu Extremwetterereignissen im Klimawandel in Deutschland, Ausgabe 2025", DMG - Deutsche Meteorologische Gesellschaft. S. 5, verfügbar unter: https://www.dmg-ev.de/wp-content/uploads/2026/02/faktenpapier_extremwetterkongress.pdf' },
    { id: 20, text: 'Bassen, A. et al. (2024): "Hauptgutachten Wasser in einer aufgeheizten Welt", WBGU - Wissenschaftlicher Beirat der Bundesregierung Globale Umweltveränderungen. S. 93-94, verfügbar unter: https://www.wbgu.de/fileadmin/user_upload/wbgu/publikationen/hauptgutachten/hg2024/pdf/wbgu_hg2024.pdf' },
    { id: 21, text: 'Bassen, A. et al. (2024): "Hauptgutachten Wasser in einer aufgeheizten Welt", WBGU - Wissenschaftlicher Beirat der Bundesregierung Globale Umweltveränderungen. S. 67-68, verfügbar unter: https://www.wbgu.de/fileadmin/user_upload/wbgu/publikationen/hauptgutachten/hg2024/pdf/wbgu_hg2024.pdf' },
    { id: 22, text: 'ZukunftsInstitut (2025): "Megatrend Urbanisierung", verfügbar unter: https://www.zukunftsinstitut.de/zukunftsthemen/megatrend-urbanisierung' },
    { id: 23, text: 'European Commission (2025): "Housing in the EU: more than 2 million new homes per year needed by 2035 to meet demand", verfügbar unter: https://joint-research-centre.ec.europa.eu/jrc-news-and-updates/housing-eu-more-2-million-new-homes-year-needed-2035-meet-demand-2025-12-16_en' },
    { id: 24, text: 'Bagheri, M. et al. (2024): "Implementing housing policies for a sufficient lifestyle", Buildings & Cities, Frauenhofer-Publica. S. 302, verfügbar unter: https://publica-rest.fraunhofer.de/server/api/core/bitstreams/27ae97e6-3071-4a7c-bb70-633e79d5fefa/content' },
    { id: 25, text: 'Schnepf, S.V., d`Hombres, B., Mauri, C. (2024): "Loneliness in Europe: Determinants, Risks and Interventions", Springer Nature. S. 3-4, verfügbar unter: https://link.springer.com/book/10.1007/978-3-031-66582-0' },
    { id: 26, text: 'Scholten, C. et al. (2025): "The future of water availability and use in the EU: A foresight study and policy options to address water scarcity", European Parliament - Directorate General for Parliamentary Research Services, Panel for the Future of Science and Technology. S. 44, verfügbar unter: https://op.europa.eu/en/publication-detail/-/publication/74d5e7d8-19a1-11f0-b1a3-01aa75ed71a1/language-en' },
    { id: 27, text: 'Europäisches Parlament (2025): "Europas Gewässer: Herausforderungen und Lösungsansätze der EU", verfügbar unter: https://www.europarl.europa.eu/topics/de/article/20250428STO28142/europas-gewasser-herausforderungen-und-losungsansatze-der-eu' },
  ],
};

export default content;
