import { BookContent } from './types';

const content: BookContent = {
  bookId: 3,
  keyPoints: [
    { text: 'Die Durchschnittliche Wohnfläche pro Person in Deutschland beträgt 47,4 m² (Stand 2021). Der Strukturelle Wohnungsmangel in Ballungsräumen und die Urbanisierung bedeuten allerdings Verdichtung auf vielen Ebenen. [3][7]', pages: [], chapters: [] },
    { text: 'Konzepte einer "Umverteilung des Raumes" sehen vor, die Wohnfläche pro Person von 2021 um etwa 2% zu reduzieren, um das Raumdefizit auszugleichen und den Neubaubedarf zu verringern sowie die Heizkosten um 24-35% zu senken. [16]', pages: [], chapters: [] },
    { text: 'Bis 2035 werden jährlich mehr als 2 Mio. neue Wohnungen in der EU benötigt. Immobilienpreise stiegen um 55% schneller als das Einkommen seit 2015. [17]', pages: [], chapters: [] },
    { text: 'Bis 2050 könnten über 216 Millionen Menschen aufgrund des Klimawandels innerhalb ihrer Länder vertrieben werden. Klimamigration beeinflusst das Leben, die Gemeinschaft und die Politik. [6]', pages: [], chapters: [] },
    { text: 'Sturmfluten und Seestürme werden weiterhin eine ernsthafte Gefahr für die nordadriatische Küste darstellen. Da Sturmflutereignisse immer häufiger werden, sind Überwachungsnetzwerke grundlegend. [29]', pages: [], chapters: [] },
  ],
  sections: [
    {
      title: 'ZUR WELT IN DIE WAGENBURG',
      bullets: [
        { text: 'Bis 2050 werden fast 84% der EU-Bürger in Städten leben, da Urbanisierung der dominante Bevölkerungstrend ist. [1]', pages: [], chapters: [] },
        { text: 'Bis 2035 werden jährlich mehr als 2 Mio. neue Wohnungen in der EU benötigt. [2]', pages: [], chapters: [] },
        { text: 'Wohnungsengpässe betreffen insbesondere städtische Regionen. [2]', pages: [], chapters: [] },
        { text: 'Die Immobilienpreise steigen seit 2015 etwa 55% schneller als das Einkommen. [2]', pages: [], chapters: [] },
        { text: 'In Deutschland stieg die durchschnittliche Wohnfläche pro Person von 14 m² (1950) auf 47,4 m² (2021). Gleichzeitig herrscht struktureller Wohnungsmangel in Ballungsräumen. Ziel ist es, 400.000 neue Wohnungen pro Jahr zu schaffen. [3]', pages: [], chapters: [] },
        { text: '71% der deutschen Bevölkerung (~60 Mio.) leben in Großstadtregionen (Stand 2022). Dabei wachsen Zentren stärker als ihr Umland, vor allem durch Zuwanderung. [4]', pages: [], chapters: [] },
        { text: 'Im Vergleich zum Jahr 2000 könnte sich die städtische Landfläche bis 2030 fast verdreifachen. Stadtgebiete dehnen sich dabei doppelt so schnell aus, wie ihre Bevölkerung. Dadurch kommt es allerdings zu Habitatsverlusten, CO₂-Emissionen und Biodiversitätsverlusten. [5]', pages: [], chapters: [] },
        { text: 'Bis 2050 könnten über 216 Mio. Menschen aufgrund des Klimawandels innerhalb ihrer Länder vertrieben werden. [6]', pages: [], chapters: [] },
        { text: 'Klimamigration verschärft den Druck auf Städte. Außerdem erkennt das EU-Recht Klimaflucht nicht als Asylgrund an. [6]', pages: [], chapters: [] },
        { text: 'Urbanisierung bedeutet Verdichtung auf vielen Ebenen. Städte stehen vor der Herausforderung, Wachstum und Lebensqualität in Einklang zu bringen. [7]', pages: [], chapters: [] },
        { text: 'Bereits heute leben über 933 Mio. Menschen in Städten mit Wasserknappheit. Diese Zahl könnte bis 2050 auf etwa 1,6-2,3 Mrd. ansteigen. [8]', pages: [], chapters: [] },
        { text: 'Städte heizen sich stärker auf als ihr ländliches Umland (städtischer Wärmeinseleffekt). Dicht besiedelte Gebiete sind besonders anfällig für Hitzewellen. Mangel an Grün- und Wasserflächen verschärft die Belastung. [9]', pages: [], chapters: [] },
        { text: 'Einsamkeit gilt als Epidemie des 21. Jahrhunderts. Alterung, steigende Zahl Alleinlebender und neue Technologien verschärfen das Phänomen. Außerdem bringt Einsamkeit negative Folgen für körperliche und psychische Gesundheit mit sich. [10]', pages: [], chapters: [] },
        { text: 'Die Nutzung sozialer Medien hat persönliche Kommunikation reduziert; online verbrachte Zeit stieg dramatisch. Technologie verändert Beziehungen. [11]', pages: [], chapters: [] },
        { text: 'U-förmiger Zusammenhang: sowohl sehr ländliche als auch sehr dicht besiedelte Gebiete weisen erhöhte Einsamkeitsraten auf. Kurze Wohndauer in einer Gemeinde erhöht Einsamkeitsrisiko signifikant. [12]', pages: [], chapters: [] },
        { text: 'Jüngere Erwachsene sind häufiger von Einsamkeit betroffen als Menschen mittleren oder höheren Alters. Übergänge (Schule zu Beruf, Renteneintritt) erhöhen Einsamkeitsrisiko. [13]', pages: [], chapters: [] },
        { text: 'Fehlende soziale Kontakte können dazu führen, dass Symptome hitzebedingter Erkrankungen unbemerkt bleiben, weshalb sziale Isolation Hitzevulnerabilität erhöht. [14]', pages: [], chapters: [] },
      ],
    },
    {
      title: 'URBANE ENTWICKLUNG',
      bullets: [
        { text: '2022 lebten 75% der EU-Bürger in Städten. Bis 2050 wird dieser Anteil auf 84% steigen, wobei Wohungsengpässe insbesondere städtische Gebiete mit hoher Nachfrage betreffen. [15]', pages: [6], chapters: [1] },
        { text: 'Die Durchschnittliche Wohnfläche pro Person in Deutschland beträgt 47,4 m² (Stand 2021). Der Strukturelle Wohnungsmangel in Ballungsräumen und die Urbanisierung bedeuten allerdings Verdichtung auf vielen Ebenen [3][7]', pages: [7, 26], chapters: [1, 2] },
        { text: 'Konzepte einer "Umverteilung des Raumes" sehen vor, die Wohnfläche pro Person von 2021 um etwa 2% zu reduzieren, um das Raumdefizit auszugleichen und den Neubaubedarf zu verringern sowie die Heizkosten um 24-35% zu senken. [16]', pages: [7, 26], chapters: [1, 2] },
        { text: 'Bis 2035 werden jährlich mehr als 2 Mio. neue Wohnungen in der EU benötigt. Immobilienpreise stiegen um 55% schneller als das Einkommen seit 2015. [17]', pages: [7, 86], chapters: [1, 7] },
        { text: 'Die aktuellsten Wohnungsengpässe sind in städtischen Gebieten mit hoher Wirtschaftsleistung oder Tourismus. [17]', pages: [8, 26], chapters: [1, 2] },
        { text: 'Die Wohndauer in einer Gemeinde beeinflusst das Einsamkeitsrisiko. [18]', pages: [8], chapters: [1] },
        { text: 'Aufgrund der Urbanisierung kommt es zu regionalen Ungleichheiten in der Verfügbarkeit von Wohnraum. In beliebten Gegenden fehlen Wohnungen, die in anderen Gebieten leerstehen. [31]', pages: [86], chapters: [7] },
        { text: 'Stadtzentren wachsen insbesondere durch Zuwanderung aus dem Ausland. [4]', pages: [86], chapters: [7] },
      ],
    },
    {
      title: 'WASSERKNAPPHEIT',
      bullets: [
        { text: 'Im Jahr 2023 waren 28% der EU-Landfläche und 32% der EU-Bevölkerung von saisonaler Wasserknappheit betroffen. Eine Verringerung bis 2030 gilt als unwahrscheinlich. [19]', pages: [5], chapters: [1] },
        { text: 'Mehr als die Hälfte der Weltbevölkerung leidet zumindest einen Teil des Jahres unter schwerem Wassermangel. In einer klimatisch aufgeheizten Welt verschärfen sich Wasserprobleme substanziell. [20]', pages: [5], chapters: [1] },
        { text: 'Digitalisierung und der Einsatz von KI werden den Wasserverbrauch in Zukunft beeinflussen. [15]', pages: [2, 3, 4, 5], chapters: [1] },
      
      ],
    },
    {
      title: 'HITZE',
      bullets: [
        { text: 'Deutschland erwärmt sich mit 2,5°C etwa doppelt so schnell wie der weltweite Durchschnitt. In Städten, besonders in dicht besiedelten Gebiten entwickeln sich eigene klimatische Bedingungen, sogenannte Wärmeinseln. Daher sind sie sehr anfällig für Hitzewellen [21]', pages: [55], chapters: [5] },
      ],
    },
    {
      title: 'NATUR & BÖDEN',
      bullets: [
        { text: 'Bodendegradation betrifft in Europa etwa 62% der Böden, wobei Wassererosion besonders bedrohlich ist. Auch küstennahe Versalzung durch den Meeresspiegelanstieg bedroht die Süßwasserreserven. [22]', pages: [52, 53, 57, 59, 96], chapters: [5, 8] },
      ],
    },
     {
      title: 'SOZIALE ISOLATION',
      bullets: [
        { text: 'Technologie hat die Beschaffenheit zwischenmenschlicher Beziehungen verändert. Ein Großteil der Einsamkeitssorgen heutzutage steht im Zusammenhang mit Kommunikationstechnologie. [10]', pages: [13], chapters: [1] },
        { text: 'Jüngere Erwachsene sind häufiger von Einsamkeit betroffen. [24]', pages: [13], chapters: [1] },
      ],
    },
     {
      title: 'EXTREMWETTER',
      bullets: [
        { text: 'Wetterextreme sind keine Jahrhundertereignisse mehr. Starkregen, Hochwasser, Stürme, Dürren und Hitze sind Teil einer neuen Realität. Extreme Wetterereignisse richten häufig großen Schaden an. [25]', pages: [10, 11, 72], chapters: [1, 5] },
        { text: 'Bis 2050 könnten über 216 Millionen Menschen aufgrund des Klimawandels innerhalb ihrer Länder vertrieben werden. Klimamigration beeinflusst das Leben, die Gemeinschaft und die Politik. [6]', pages: [36, 72], chapters: [3, 5] },
        { text: 'Klimabedingte Vertreibung ist keine Hypothese mehr. Bereits 2022 wurden 32,6 Mio. Menschen vertrieben. [6]', pages: [39, 98], chapters: [3, 8] },
        { text: 'Sturmfluten in der nördlichen Adria treten häufiger auf. Das Phänomen verursacht Überschwemmungen der gesamten Flachküste. Durch den Klimawandel wird dieses Phänomen häufiger und intensiver. [26]', pages: [52, 53, 72], chapters: [5, 6] },
        { text: 'Die Häufigkeit und Intensität von Hitzewellen und Dürren werden in den meisten Regionen Europas bis Mitte des Jahrhunderts zunehmen. [15]', pages: [55], chapters: [5] },
        { text: 'Laut EUA verursachten wetter- und klimabedingte Extremereignisse in EU-Staaten zwischen 1980 und 2021 wirtschaftliche Verluste von ca. 560 Mrd. Euro. [27]', pages: [56, 57, 72], chapters: [5, 6] },
        { text: 'Zwischen 1901 und 2018 ist der Meeresspiegel um etwa 20 cm angestiegen. Niedrig liegende Küsten und Inseln sind von häufigeren Sturmfluten betroffen. [28]', pages: [58, 59], chapters: [5] },
        { text: 'Sturmfluten und Seestürme werden weiterhin eine ernsthafte Gefahr für die nordadriatische Küste darstellen. Da Sturmflutereignisse immer häufiger werden, sind Überwachungsnetzwerke grundlegend. [29]', pages: [81, 107, 108, 109], chapters: [7, 9] },
        { text: 'Überschwemmungen haben unmittelbare Folgen. Sie sorgen für Verletzungen (unter Umständen sogar tödlich), den Verlust des Wohngebäudes oder der Heimat sowie psychische Auswirkungen (Angstzustände, PTBS). [30]', pages: [83], chapters: [7] },
        { text: 'Klimabedingte Vertreibung verschärft den Druck auf Städte. Der Klimawandel wirkt als Bedrohungsverstärker und verschärft bestehende sozioökonomsiche Spannungen. [6]', pages: [86], chapters: [7] },
        { text: 'Hochwasserereignisse gehören zum Naturgeschehen, treten aber aufgrund der globaen Erwärmung häufiger auf. [32]', pages: [87, 88, 89, 90], chapters: [7] },
      ],
    },
  ],
  sources: [
    { id: 1, text: 'Scholten, C. et al. (2025): "The future of water availability and use in the EU: A foresight study and policy options to address water scarcity", European Parliament - Directorate General for Parliamentary Research Services, Panel for the Future of Science and Technology. S. 43, verfügbar unter: https://op.europa.eu/en/publication-detail/-/publication/74d5e7d8-19a1-11f0-b1a3-01aa75ed71a1/language-en' },
    { id: 2, text: 'European Commission (2026): "Water scarcity and droughts: Preventing and mitigating water scarcity and droughts in the EU", verfügbar unter: https://environment.ec.europa.eu/topics/water/water-scarcity-and-droughts_en' },
    { id: 3, text: 'Bagheri, M. et al. (2024): "Implementing housing policies for a sufficient lifestyle", Buildings & Cities, Frauenhofer-Publica. S. 301-302, verfügbar unter: https://journal-buildingscities.org/articles/10.5334/bc.435' },
    { id: 4, text: 'Destatis - Statistisches Bundesamt (2026): "Bevölkerung - Großstadtregionen im Wandel", verfügbar unter: https://www.destatis.de/DE/Themen/Querschnitt/Demografischer-Wandel/Aspekte/demografie-grossstadtregionen.html' },
    { id: 5, text: 'Seto, K.C., Güneralp, B., & Hutyra, L.R. (2012): "Global forecasts of urban expansion to 2030 and direct impacts on biodiversity and carbon pools", PNAS. S. 16083-16085, verfügbar unter: https://www.pnas.org/doi/full/10.1073/pnas.1211658109' },
    { id: 6, text: 'Drakokhrust, T. (2025): "Climate Migration and EU Policy: Is the European Union Ready for New Challenges?", Globalising Southeast Europe Research Blog, verfügbar unter: https://global-sees.org/2025/07/24/climate-migration-and-eu-policy-is-the-european-union-ready-for-new-challenges/' },
    { id: 7, text: 'ZukunftsInstitut (2025): "Megatrend Urbanisierung", verfügbar unter: https://www.zukunftsinstitut.de/zukunftsthemen/megatrend-urbanisierung' },
    { id: 8, text: 'Bassen, A. et al. (2024): "Hauptgutachten Wasser in einer aufgeheizten Welt", WBGU - Wissenschaftlicher Beirat der Bundesregierung Globale Umweltveränderungen. S. 6, verfügbar unter: https://www.wbgu.de/fileadmin/user_upload/wbgu/publikationen/hauptgutachten/hg2024/pdf/wbgu_hg2024.pdf' },
    { id: 9, text: 'DWD - Deutscher Wetterdienst (2025): "Was wir über das Extremwetter in Deutschland wissen: Stand der Wissenschaft zu Extremereignissen im Klimawandel in Deutschland, Ausgabe 2025", DMG - Deutsche Meteorologische Gesellschaft. S. 11, verfügbar unter: https://www.dmg-ev.de/wp-content/uploads/2026/02/faktenpapier_extremwetterkongress.pdf' },
    { id: 10, text: 'Schnepf, S.V., d`Hombres, B., Mauri, C. (2024): "Loneliness in Europe: Determinants, Risks and Interventions", Springer Nature. S. 3-4, verfügbar unter: https://link.springer.com/book/10.1007/978-3-031-66582-0' },
    { id: 11, text: 'Schnepf, S.V., d`Hombres, B., Mauri, C. (2024): "Loneliness in Europe: Determinants, Risks and Interventions", Springer Nature. S. 93, verfügbar unter: https://link.springer.com/book/10.1007/978-3-031-66582-0' },
    { id: 12, text: 'Schnepf, S.V., d`Hombres, B., Mauri, C. (2024): "Loneliness in Europe: Determinants, Risks and Interventions", Springer Nature. S. 51-52, verfügbar unter: https://link.springer.com/book/10.1007/978-3-031-66582-0' },
    { id: 13, text: 'Schnepf, S.V., d`Hombres, B., Mauri, C. (2024): "Loneliness in Europe: Determinants, Risks and Interventions", Springer Nature. S. 44, 171, verfügbar unter: https://link.springer.com/book/10.1007/978-3-031-66582-0' },
    { id: 14, text: 'Landeshauptstadt Stuttgart - Gesundheitsamt und Amt für Umweltschutz (2025): "Hitzeaktionsplan der Landeshauptstadt Stuttgart", Stadtklima Stuttgart. S. 18, verfügbar unter: https://www.stadtklima-stuttgart.de/index.php?klima_kliks_hitzeaktionsplan_stuttgart_2025#:~:text=Download%3A%20Hitzeaktionsplan%20Stuttgart%20Juni%202025%20(pdf%2C%2017%20MB)' },
    { id: 15, text: 'Scholten, C. et al. (2025): "The future of water availability and use in the EU: A foresight study and policy options to address water scarcity", European Parliament - Directorate General for Parliamentary Research Services, Panel for the Future of Science and Technology, verfügbar unter: https://op.europa.eu/en/publication-detail/-/publication/74d5e7d8-19a1-11f0-b1a3-01aa75ed71a1/language-en' },
    { id: 16, text: 'Bagheri, M. et al. (2024): "Implementing housing policies for a sufficient lifestyle", Buildings & Cities, Frauenhofer-Publica. S. 301, 309, verfügbar unter: https://journal-buildingscities.org/articles/10.5334/bc.435' },
    { id: 17, text: 'European Commission (2025): "Housing in the EU: more than 2 million new homes per year needed by 2035 to meet demand", Joint Research Centre, verfügbar unter: https://joint-research-centre.ec.europa.eu/jrc-news-and-updates/housing-eu-more-2-million-new-homes-year-needed-2035-meet-demand-2025-12-16_en' },
    { id: 18, text: 'Schnepf, S.V., d`Hombres, B., Mauri, C. (2024): "Loneliness in Europe: Determinants, Risks and Interventions", Springer Nature. S. 52, verfügbar unter: https://link.springer.com/book/10.1007/978-3-031-66582-0' },
    { id: 19, text: 'European Environment Agency (2025): "Water scarcity conditions in Europe", verfügbar unter: https://www.eea.europa.eu/en/analysis/indicators/use-of-freshwater-resources-in-europe-1' },
    { id: 20, text: 'Bassen, A. et al. (2024): "Hauptgutachten Wasser in einer aufgeheizten Welt", WBGU - Wissenschaftlicher Beirat der Bundesregierung Globale Umweltveränderungen. S. 5, 30, verfügbar unter: https://www.wbgu.de/fileadmin/user_upload/wbgu/publikationen/hauptgutachten/hg2024/pdf/wbgu_hg2024.pdf' },
    { id: 21, text: 'DWD - Deutscher Wetterdienst (2025): "Was wir über das Extremwetter in Deutschland wissen: Stand der Wissenschaft zu Extremereignissen im Klimawandel in Deutschland, Ausgabe 2025", DMG - Deutsche Meteorologische Gesellschaft. S. 5, 11, verfügbar unter: https://www.dmg-ev.de/wp-content/uploads/2026/02/faktenpapier_extremwetterkongress.pdf' },
    { id: 22, text: 'Prăvălie, R. et al. (2026): "A pan-European spatial inventory of agricultural land degradation", International Soil and Water Conservation Research, Elsevier. S. 1, verfügbar unter: https://www.sciencedirect.com/science/article/pii/S2095633926000055?via%3Dihub' },
    { id: 23, text: 'Bassen, A. et al. (2024): "Hauptgutachten Wasser in einer aufgeheizten Welt", WBGU - Wissenschaftlicher Beirat der Bundesregierung Globale Umweltveränderungen. S. 74, verfügbar unter: https://www.wbgu.de/fileadmin/user_upload/wbgu/publikationen/hauptgutachten/hg2024/pdf/wbgu_hg2024.pdf' },
    { id: 24, text: 'Schnepf, S.V., d`Hombres, B., Mauri, C. (2024): "Loneliness in Europe: Determinants, Risks and Interventions", Springer Nature. S. 171, verfügbar unter: https://link.springer.com/book/10.1007/978-3-031-66582-0' },
    { id: 25, text: 'Bundesministerium für Umwelt, Klimaschutz, Naturschutz und nukleare Sicherheit (2025): "Die Deutsche Anpassungsstrategie an den Klimawandel", verfügbar unter: https://www.bundesumweltministerium.de/themen/klimaanpassung/die-deutsche-anpassungsstrategie-an-den-klimawandel' },
    { id: 26, text: 'Lionello, P., Galati, M.B., Elvini, E. (2012): "Extreme storm surge and wind wave climate scenario simulations at the Venetian littoral", Physics and Chemistry of the Earth 40-41, Elsevier. S. 86, verfügbar unter: https://www.sciencedirect.com/science/article/pii/S1474706510000665?via%3Dihub' },
    { id: 27, text: 'Bassen, A. et al. (2024): "Hauptgutachten Wasser in einer aufgeheizten Welt", WBGU - Wissenschaftlicher Beirat der Bundesregierung Globale Umweltveränderungen. S. 83, verfügbar unter: https://www.wbgu.de/fileadmin/user_upload/wbgu/publikationen/hauptgutachten/hg2024/pdf/wbgu_hg2024.pdf' },
    { id: 28, text: 'Bassen, A. et al. (2024): "Hauptgutachten Wasser in einer aufgeheizten Welt", WBGU - Wissenschaftlicher Beirat der Bundesregierung Globale Umweltveränderungen. S. 36, verfügbar unter: https://www.wbgu.de/fileadmin/user_upload/wbgu/publikationen/hauptgutachten/hg2024/pdf/wbgu_hg2024.pdf' },
    { id: 29, text: 'Mel, R.A. et al. (2023): "Insights on the Extreme Storm Surge Event of the 22 November 2022 in the Venice Lagoon", Journal of Mariene Science and Engineering, 11(9), 1750, MDPI. S. 2, verfügbar unter: https://www.mdpi.com/2077-1312/11/9/1750' },
    { id: 30, text: 'Bassen, A. et al. (2024): "Hauptgutachten Wasser in einer aufgeheizten Welt", WBGU - Wissenschaftlicher Beirat der Bundesregierung Globale Umweltveränderungen. S. 93, verfügbar unter: https://www.wbgu.de/fileadmin/user_upload/wbgu/publikationen/hauptgutachten/hg2024/pdf/wbgu_hg2024.pdf' },
    { id: 31, text: 'Bagheri, M. et al. (2024): "Implementing housing policies for a sufficient lifestyle", Buildings & Cities, Frauenhofer-Publica. S. 302, verfügbar unter: https://journal-buildingscities.org/articles/10.5334/bc.435' },
    { id: 32, text: 'Bundesministerium für Umwelt, Klimaschutz, Naturschutz und nukleare Sicherheit (2026): "Hochwasservorsorge und Management von Hochwasserrisiken", verfügbar unter: https://www.bundesumweltministerium.de/themen/wasser-und-binnengewaesser/hochwasservorsorge' },
  ],
};

export default content;
