import { BookContent } from './types';

const content: BookContent = {
  bookId: 1,
  keyPoints: [
    { text: 'Die Nachfrage nach Wasser wird sich laut UNESCO (2023) jährlich um ca. 1% erhöhen. Im Jahr 2050 wäre das ein Zuwachs von 20-30%. [11]', pages: [], chapters: [] },
    { text: 'Simulationen zeigen eine starke Zunahme extremer Dürren ab den 2030er Jahren bis zwischen 2081 und 2100 kein Jahr in Deutschland mehr nicht als extrem trocken eingestuft wird. [27]', pages: [], chapters: [] },
    { text: 'Extremwetterereignisse wie Hitzewellen, Dürren oder Starkregen werden global betrachtet häufiger, heftiger und treten schnell sowie in kürzeren Zeiträumen auf. [32]', pages: [], chapters: [] },
    { text: 'Auch in Deutschland kommt es durch den Klimawandel zu früheren und trockeneren Sommern mit gravierenden Auswirkungen auf Landwirtschaft und Ernteerträge sowie die Wirtschaft und Ökologie im allgemeinen. [14][43]', pages: [], chapters: [] },
    { text: 'Das globale Phänomen der Landflucht beschreibt eine zunehmende Urbanisierung, da Menschen nach wirtschaftlichen Chancen und dem Zugang zu Dienstleistungen suchen. [46]', pages: [], chapters: [] },
  ],
  sections: [
    {
      title: 'ZUR WELT IN DAS FAHRWASSER',
      bullets: [
        { text: 'Wasser wird in Deutschland zunehmend knapp. Jeder zweite Landkreis ist von Wasserstress betroffen (v.A. Lankreise mit intensiver Landwirtschaft, Industrie oder dichter Besiedelung.) [0]', pages: [], chapters: [] },
        { text: 'Wasserknappheit gilt als größte Herausforderung in der Wasserversorgungssicherheit. [1]', pages: [], chapters: [] },
        { text: '28% der EU waren 2023 von Wasserknappheit betroffen. [2]', pages: [], chapters: [] },
        { text: '2023 waren insbesondere Flussteilgebiete von Wasserknappheit betroffen, auch in Deutschland. [2]', pages: [], chapters: [] },
        { text: 'Wasserknappheit betrifft nicht nur Südeuropa sondern die gesamte EU. [2]', pages: [], chapters: [] },
        { text: 'Während der letzten zehn Jahren hat die Häufigkeit und Schwere von Dürren zugenommen, was negative Folgen für die Wasserverfügbarkeit hat. [2]', pages: [], chapters: [] },
        { text: 'Wasserknappheit und Dürren werden in der EU immmer häufiger und flächendeckender. [3]', pages: [], chapters: [] },
        { text: 'Die Herausforderungen um Wasserknappheit verschärfen sich, Unsicherheit wird Normalität und die Anpassungsfähigkeit könnte überschritten werden. [4]', pages: [], chapters: [] },
        { text: 'In heutigen Städten sind mehr als 933 Millionen Menschen von Wasserknappheit betroffen. [5]', pages: [], chapters: [] },
        { text: '2050 werden 30-50% der Weltbevökerung von Wasserknappheit in Städten betroffen sein. [5]', pages: [], chapters: [] },
        { text: 'Die urbane Wassernachfrage wächst bis 2050 um 80%. [5]', pages: [], chapters: [] },
        { text: 'Gründe für urbanen Wassermangel sind: Mangel an Oberflächenwasser, Bodenversiegelung, Grundwasserübernutzung sowie höherer Wasserbedarf aufgrund von Urbanisierung und steigendem Pro-Kopf-Verbrauch. [5]', pages: [], chapters: [] },
        { text: '2050 könnten 1,6 bis 2,3 Mrd. Menschen von Wasserknappheit betroffen sein. [5]', pages: [], chapters: [] },
        { text: 'Der Mensch verteilt Wasser ungerecht und verschmutzt und übernutzt es vielerorts. [6]', pages: [], chapters: [] },
        { text: 'Die ungleiche Verteilung von Wasser äußert sich in der Übernutzung der Wasserressourcen, z.B. durch einkommensstarke Bevölkerungsgruppen im urbanen Raum. [7]', pages: [], chapters: [] },
        { text: 'Schon heute sind die Auswirkungen des Klimawandels auf die Wasserversorgung spürbar. [6]', pages: [], chapters: [] },
        { text: 'Weltweit haben etwa 2,2 Mrd. Menschen keinen Zugang zu sauberem Trinkwasser, insbesondere in ländlichen Gebieten. [6]', pages: [], chapters: [] },
        { text: 'Etwa 3,5 Mrd. Menschen verfügen über keinen ausreichenden Zugang zu sanitären Einrichtungen. [6]', pages: [], chapters: [] },
        { text: 'Stärekere Hitzewellen maximieren den täglichen Wasserverbrauch, was die Kapazität von Aufbereitungsanlagen und Verteilsystemen überlastet. Die Konsequenz sind vorübergehende Versorgungsengpässe und möglicherweise Nutzungslimits. [8]', pages: [], chapters: [] },
        { text: 'Trinkwasserversorgungssysteme beschränken sich häufig auf eine Ressource (z.B. Grundwasser). Wenn diese ausfällt (z.B. durch Dürre) kann das zu Engpässen führen. [8]', pages: [], chapters: [] },
        { text: 'Wasserknappheit und Nutzungslimits sind kein Problem der Zukunft: In der Wasserkrise von Kapstadt (2015-2018) wurde der Wasserverbrauch aufgrund extremer Dürre und sinkendem Pegel, der für die Trinkwasserversorgung genutzten Talsperre, zeitweise auf 50 Liter pro Person pro Tag begrenzt. [8]', pages: [], chapters: [] },
        { text: 'Durch Dürre und Hitze (z.B. Verdunstung) können Schadstoffe in Oberflächengewässern nicht richtig verdünnt werden, wodurch die Wasserqualität sinkt. [9]', pages: [], chapters: [] },
        { text: 'Mit dem Klimawandel entsteht eine schwer beherrschbare Krise der Wasserverfügbarkeit, die erhebliche Folgen für das Ökosystem und den Menschen mit sich bringt. [9]', pages: [], chapters: [] },
        { text: 'Ohne Maßnahmen könnte sich die jährlich in die Umwelt gelangende Kuststoffmenge bis 2060 weltweit auf etwa 44 Mio. Tonnen erhöhen, wodurch auch die Belastung durch Mikro- und Nanoplastik erheblich zunehmen würde. Das wiederum hätte negative Auswirkungen auf die Wasserqualität. [10]', pages: [], chapters: [] },
        { text: 'Die Nachfrage nach Wasser wird sich laut UNESCO (2023) jährlich um ca. 1% erhöhen. Im Jahr 2050 wäre das ein Zuwachs von 20-30% [11]', pages: [], chapters: [] },
        { text: 'Durch die globale Erwärmung nehmen die Bodenfeuchte und grünes Wasser (z.B. Regenwasser) ab, was sich auf die gesamte Wasserverfügbarkeit auswirkt. [12]', pages: [], chapters: [] },
        { text: 'Kommt es als Reaktion auf den Klimawandel zu einer steigenden Grundwasserentnahme, könnten durch die Übernutzung Grundwasseranteile auf der ganzen Welt knapp werden. [12]', pages: [], chapters: [] },
        { text: 'Bis Ende des Jahrhunderts kann mit anhaltenden Perioden geringer Grundwasserstände gerechnet werden. [13]', pages: [], chapters: [] },
        { text: 'Auch in Regionen wie Deutschland, in denen das Wasseraufkommen eher hoch ist, führt der Klimawandel zunehmend zu Wasserstress, insbesondere durch heiße, trockene Sommer. [14]', pages: [], chapters: [] },
        { text: 'Grundwasser ist in Deutschland mit fast 70% die wichtigste Trinkwasserquelle. 2019 wurden in Deutschland 62,4% des Trinkwassers aus dem Grundwasser, 12,6% aus See- und Talsperren, 8% aus angereichertem Grundwasser, Uferfiltrat und Quellwasser sowie 1,2% aus Flusswasser gewonnen. [14][15]', pages: [], chapters: [] },
        { text: 'Im Jahr 2019 nutzte die an die Wasserversorgung angeschlossene Bevölkerung etwa 128 Liter pro Person pro Tag. [16]', pages: [], chapters: [] },
        { text: 'Durch den Klimawandel und dadurch häufiger auftretenden Hitzewellen und Dürren, wird es in Deutschland zunehmend zu regionaler Wasserknappheit und Wassernutzungskonflikten kommen. [17]', pages: [], chapters: [] },
        { text: '2022 waren hauptsächlich PrivatverbraucherInnen von Wassernutzungskonflikten betroffen (v.A. durch Entnahmeverbote oder kurzfristige Abhängigkeit von einer Trinkwasser-Ersatzversorgung). [18]', pages: [], chapters: [] },
        { text: 'Dürren werden als "neue Normalität" häufiger und länger auftreten. [19]', pages: [], chapters: [] },
        { text: 'Viele Regionen in Deutschland sind bereits von Wasserknappheit und Wassernutzungskonflikten betroffen. Der Klimawandel und ein steigender Bedarf verschärfen die Situation, insbesondere während Trockenperioden.[19]', pages: [], chapters: [] },
        { text: 'Ein Ansatz zur Erweiterung des Wasserangebots ist die Meerwasserentsalzung, die allerdings Nebeneffekte hat. [20]', pages: [], chapters: [] },
        { text: 'Bei Meerwasserentnahme und Rückführung wird das Wasserökosystem belastet. [21]', pages: [], chapters: [] },
        { text: 'Durch fortschreitenden Klimawandel und Wasserverschmutzung one Schutz- und Regulierungsmaßnahmen ist langfristig mit erheblichen Risiken für die Wasserversorgung der Bevölkerung mit qualitativ geeignetem Wasser zu rechnen. [22]', pages: [], chapters: [] },
        { text: 'In Zukunft wird voraussichtlich mehr Wasser aus Meeren, Böden und anderen Wasseroberflächen verdunsten. Gleichzeitig kann die Atmosphäre immer größere Mengen Wasser aufnehmen. Dadurch geht an vielen Orten weltweit mehr Wasser von der Erdoberfläche verloren. [22]', pages: [], chapters: [] },
        { text: 'Der Verlust von Grundwasser kann Wassermangel verstärken, Grundwasserversalzung verursachen, zum Versiegen von Brunnen beitragen, Ökosysteme die vom Grundwasser abhängen schädigen, das Eindringen von Abwasser ins Grundwasser begünstigen sowie zum Verlust von Vegetation und Biodiversität beitragen. [22]', pages: [], chapters: [] },
        { text: 'Insbesondere Süd- und Mitteleuropa verlieren schnell an Wasserreserven. Die Südhälfte Europas von Spanien bis Deutschland wird immer trockener [23]', pages: [], chapters: [] },
      ],
    },

    {
      title: 'WASSERKNAPPHEIT',
      bullets: [
        { text: 'Wasser ist ein knappes, begehrtes und ungleich verteiltes Gut. [24]', pages: [4, 65, 41], chapters: [1, 5, 8] },
        { text: 'Einkommensstarke Bevölkerungsgruppen im urbanen Raum verbrauchen mehr Wasser als andere Gruppen (Übernutzung). [2]', pages: [4], chapters: [1] },
        { text: 'Der Wasserverbrauchsindes Plus (WEI+) zeigt, wie stark die verfügbaren Wasservorräte genutzt werden. Er macht deutlich, ob in einer Region genug Süßwasser vorhanden ist oder ob bereits Wassermangel droht. Wenn mehr als 20% des verfügbaren Wassers verbraucht werden, gilt das Gebiet bereits als belastet. Steigt der Wert über 40%, wird so viel Wasser genutzt, dass dies auf Dauer problematisch und möglicherweise nicht mehr umweltverträglich ist. [2]', pages: [5], chapters: [1] },
        { text: 'Etwa 2,2 Mrd. Menschen haben keinen sicheren Zugang zu Trinkwasser, insbesondere Menschen mit geringerem Einkommen (UNESCO, 2024). [6]', pages: [13], chapters: [1] },
        { text: 'Insbesondere in ländlichen Gebieten ist die Versorgungslage eine Herausforderung. [6]', pages: [13], chapters: [1] },
        { text: 'In einigen Regionen Deutschlands muss die bewässerte Fläche in Zukunft limitiert werden um in der zweiten Hälfte des 21. Jahrunderts die öffentliche Wasserversorgung auch bei Grundwasserknappheit sicherzustellen. [25]', pages: [27], chapters: [3] },
        { text: 'Zu diesen Regionen zählen unter anderem Regionen im Oberrheingraben, im westlichen Nordrhein-Westfalen, im südöstlichen Niedersachsen, im mitteldeutschen Trockengebiet sowie Brandenburg und Mecklemburg-Vorpommern. [25]', pages: [27], chapters: [3] },
        { text: 'Durch sinkende Grundwasserspiegel und Niedrigwasserperioden über einen längeren Zeitraum können Nutzungskonflikte zwischen Haushalten, Industrie, Landwirtschaft und Wasserökosystemen enstehen oder verschärft werden. [26]', pages: [27], chapters: [3] },
        { text: 'Simulationen zeigen eine starke Zunahme extremer Dürren ab den 2030er Jahren bis zwischen 2081 und 2100 kein Jahr in Deutschland nicht als extrem trocken eingestuft wird. [27]', pages: [36], chapters: [4] },
        { text: 'Fehlender Zugang zu sauberem Trinkwasser wirkt sich bei älteren Menschen häufig schneller lebensverkürzend aus, als bei jungen Menschen. [28]', pages: [38, 39], chapters: [4, 5] },
        { text: 'Wasserknappheit in Kapstadt 2015: Der Wasserverbrauch wurde vorübergehend auf 50 Liter pro Person pro Tag begrenzt. [8]', pages: [41, 65], chapters: [5, 8] },
        { text: 'Eine mangelhafte Wasserversorgung beeinträchtigt neben der Vitalität und Leistung eines Menschen auch die Leistung der Gesellschaft, was zu wirtschaftlichen und gesellschaftspolitischen Konzequenzen führen kann. [5]', pages: [44, 72, 73], chapters: [5, 9] },
        { text: 'Dehydration ist die Konsequenz von Wassermangel und wenn der Körper nicht mehr in der Lage ist die übermäßige Hitze zu auszugelichen. [29]', pages: [56], chapters: [7] },
        { text: 'Etwa die Hälfte des Jahres leidet rund die Hälfte der globalen Bevölkerung unter Wassermangel. [30]', pages: [65, 56, 41], chapters: [8, 5, 7] },
        { text: 'Durch Hitzewellen kommt es zu höherem maximalem Wasserverbrauch pro Tag, wofür die Kapazität von Aufbereitungsanlagen und Verteilungsnetze nicht ausgelegt sind. Daher kommt es zu Nutzungslimits. [8]', pages: [65, 41], chapters: [8, 5] },
        { text: '"Wasser ist der Blutkreislauf der Biosphäre" (Ripl., 2003). [30]', pages: [72, 73], chapters: [9] },
        { text: 'Klimaextreme werden häufiger, darunter auch das Auftreten von Starkregenereignissen. [31]', pages: [72, 73], chapters: [1, 5, 8] },
        { text: 'Extremereignisse wie Hitzewellen, Dürren oder Starkregen werden global betrachtet häufiger, heftiger, treten schneller auf und in kürzeren Zeiträumen. [32]', pages: [72, 73], chapters: [9] },
        { text: 'Starkregenereignisse werden häufiger und intensiver, besonders in Nordamerika, Europa und Asien. [32]', pages: [72, 73], chapters: [9] },
        { text: 'Starkregen und Hochwasser sind keine Jahrhundertereignisse mehr sondern Teil der neuen Realität. [33]', pages: [72, 73], chapters: [9] },
      ],
    },
    {
      title: 'HITZE',
      bullets: [
        { text: 'Der Klimawandel wird die hitzebedingte Erkrankungs- und Sterbraten erhöhen und das Gesundheitssystem vor Herausforderungen stellen. [34]', pages: [4], chapters: [1] },
        { text: 'Bei der derzeitigen Klimapolitik und einem Anstieg der globalen Temperaturen um 3°C könnten sich die hitzebedingten Todesfälle bis 2100 auf 24.112-80.676 erhöhen. [34]', pages: [4], chapters: [1] },
        { text: 'Menschen ab 85 Jahren sind besonders gefährdet, da sie anfälliger für extreme Temperaturen sind. [35]', pages: [4], chapters: [1] },
        { text: 'Die Temperaturen sind in Deutschland stärker gestiegen als im weltweiten Durchschnitt. [36]', pages: [5], chapters: [1] },
        { text: 'Der schnellere Temperaturanstieg liegt daran, dass sich Landregionen schneller erwärmen als Meere. [36]', pages: [5], chapters: [1] },
        { text: 'Klimaprojektionen zeigen für Deutschland zwischen 2071 und 2100 einen Anstieg der Temperaturen von 3,1 bis 4,7°C. [36]', pages: [5], chapters: [1] },
        { text: 'Europa ist der Kontinent mit der stärksten globalen Erwärmung. In Deutschland sind die Temperaturen bereits um 2,5°C gestiegen. [37]', pages: [5], chapters: [1] },
        { text: 'Wird der Treibhausgasausstoß nicht reduziert, können sich die heißen Tage 2031-2060 in Norddeutschland auf fünf bis zehn, in Süddeutschland auf zehn bis zwanzig erhöhen. [38]', pages: [5, 15], chapters: [1, 2] },
        { text: 'Intensive Hitzewellen haben in den vergangenen Jahrzehnten zugenommen. [38]', pages: [15], chapters: [2] },
        { text: 'Aufgrund von dichter Bebauung, versiegelten Flächen, Abwärme durch Häuser und Verkehr sowie einen Mangel an Grün- und Wasserflächen entwicklen sich Städte zu Wärmeinseln, die höhere Temepraturen aufweisen, als die ländliche Umgebung. [39]', pages: [20, 21], chapters: [2] },
        { text: 'Häufigkeit, Intensität und Dauer von Hitzewelllen nehmen in Europa inbesondere im Binnenland aufgrund von Oberflächenerwärmung zu. [40]', pages: [35], chapters: [4] },
        { text: 'Wärme wird durch Gebäude und asphaltierte Straßen tagsüber besser gespeichert, als durch natürliche Oberflächen. Planzen wirken durch Verdunstung kühlend. [39]', pages: [34, 35], chapters: [4] },
        { text: 'Personen ab 65 machen mehr als 92,7% der hitzebedingten Todesfälle aus. [41]', pages: [38], chapters: [4] },
      ],
    },
    {
      title: 'NATUR & BODEN',
      bullets: [
        { text: 'Dürreereignisse werden häufiger und intensiver werden. [2][3]', pages: [12], chapters: [1] },
        { text: 'Wegen Hitze und Trockenheit kommt es zunehmend zu Waldsterben, wodurch auch die wasserspeichernden Eigenschaften des Waldes verloren gehen und die Waldbrandgefahr zunimmt. [42]', pages: [12], chapters: [1] },
        { text: 'Die Anzahl aufgrund von Trockenheit geschädigter Bäume steigt jährlich an, da die Anpassungsgrenze einiger Arten überschritten wird. Das Betrifft auch die Vegetation insgesamt. [44]', pages: [62], chapters: [8] },
        { text: 'Auch in wasserreichen Gebieten wie Deutschland kommt es durch den Klimawandel zu immer heißeren, früheren und trockeneren Sommern. Das hat gravierende Auswirkungen auf die Landwirtschaft und die Ernteerträge, sowie die Wirtschaft und Ökologie im Allgmeinen. [14][43]', pages: [32], chapters: [4] },
        { text: 'Durch lang anhaltende, heiße und häufige Dürreperioden kann zu Schwierigkeitn in der Produktivität des Ernährungssystems und landwirtschaftlicher Zyklen kommen, darunter im Pflanzenabau, der Tierhaltung sowie der Aquakultur. [14]', pages: [32], chapters: [4] },
        { text: 'Die Landwirtschaft ist die häufigste Landnutzungsart der Welt und beträgt fast 50% der kultivierbaren Flächen. [20]', pages: [32,33], chapters: [4] },
        { text: 'Die Umwandlung von Feldern in Siedlungsflächen führt zu einer steigenden Bodenverdichtung, Waldabholzung und einer Verringerung der Vegetationsdecke, wodurch der Wasserabluss verändert und der Wasserkreislauf beeinflusst wird. [20]', pages: [32,33], chapters: [4] },
        { text: 'Durch zunehmende Versiegelung von Oberflächen werden Abflüsse schneller und die Gefahr für Überschwemmungen steigt an. [20]', pages: [32,33], chapters: [4] },
        { text: 'Auch Bodendegradationsprozesse wie Bodenerosion oder Nährstoffverarmung wirken sich auf die Fähigkeit und Qualität der Wasserspeicherung aus. [20]', pages: [32,33], chapters: [4] },
        { text: 'Lange andauernde Dürreperioden verändern den Bodenfeuchtegehalt und können zum Versiegen von Quellwasserverschüttungen führen, wodurch (Grund-)Wasserstände zurückgehen. Diese Entwicklungen gefährden die Trinkwassersicherheit. [8]', pages: [36], chapters: [4] },
        { text: 'Mit den Temperaturen steigt auch der Wasserbedarf der Vegetation und kann im schlimmsten Fall nicht mehr durch Bodenfeuchte und Niederschlag gedeckt werden. Als Konsequenz könnten es zu einer Ausweitung von Trockenwäldern, Steppenbildung und schließlich Wüstenlandschaften kommen. [44]', pages: [62], chapters: [8] },
      ],
    },
    {
      title: 'URBANE ENTWICKLUNG',
      bullets: [
        { text: 'Der Trend der sogenannten Urbanisierung wird bis 2030 und wahrscheinlich darüber hinaus weitergehen. Bis 2050 könnten etwa 84% der EU-Bürger in Städten leben. [45]', pages: [3], chapters: [1] },
        { text: 'Demografische und gesellschaftliche Veränderungen bis 2050 können in Europa unter anderem durch Urbanisierung, Migration und sozialer Ungleichheit auf regionaler Ebene und innerhalb von Bevölkerungsgruppen auftreten. [46]', pages: [3], chapters: [1] },
        { text: 'Dieser Trend lässt sich auch in den Zahlen der letzten Jahren deutlich erkennen. 2022 lebten etwa 3,3 Mio. Menschen mehr in Großstädten, wobei insbesondere Zentren einen Zuwachs von etwa 7,4 Prozent erfahrenhaben. Im Vergleich zu 2012 leben etwa 5,8 Prozent mehr Menschen in Deutschland in Großstadtregionen. Auch Gebiete, die an Städte angrenzen sind in der Bevölkerungszahl gestiegen. [52]', pages: [24,27,36,37,63], chapters: [3,4,8] },
        { text: 'Die Größe von Häusern und Wohnfläche ist entscheidend für den Energieverbrauch. [47]', pages: [3], chapters: [1] },
        { text: 'Die Wohnfläche pro Kopf ist in den letzten Jahren stark angestiegen und beträgt aktuell in Deutschland etwa 46 m². Durch eine Minimierung dieser Fläche auf 30 m² könnte der Heizenergiebedarf um bis zu 35% reduziert werden. [48]', pages: [3], chapters: [1] },
        { text: 'Global zeichnet sich ein Muster der sog. Landflucht ab. Menschen ziehen auf der Suche nach besseren wirtschaftlichen Chancen und Zugang zu Dienstleistungen in Städte. [46]', pages: [24,27,36,37,63,65,66,69], chapters: [3,4,8] },
        { text: 'Schon heute leben mehr Menschen in Städten als in ländlichen Gebieten. Bis 2050 könnten bis zu 75% der globalen Bevölkerung in Sätdten leben. [54]', pages: [24,27,36,37,63,65,66,69], chapters: [3,4,8] },
        { text: 'Gemeinsam mit der Migration innerhalb und außerhalb der EU wird ein starker Druck auf die Wasserversorgung und das Ressourcenmanagement in Städten ausgeübt, um die Versorgung der steigenden Bevölkerung sowie der Industrie zu gewährleisten. [46]', pages: [24,27,36,37,63], chapters: [3,4,8] },
        { text: 'Bedingt durch den Klimawandel könnten sich auch die Lebensbedingungen negativ verändern wodurch Lebensunterhalt und Ernährung an Orten gefährdet werden können. [53]', pages: [24,27,36,37,63,65,66], chapters: [3,4,8] },
      ],
    },
    {
      title: 'SOZIALE ISOLATION',
      bullets: [
        { text: 'Eine alternde Bevölkerung, neue Technologien sowie ein Anstieg der alleinlebenden Menschen können Einsamkeit verstärken. [49]', pages: [12,13], chapters: [1] },
        { text: 'Soziale Medien verändern die Art und Weise, wie Menschen miteinander kommunizieren und interagieren. Persönliche Kommunikation geht zunehmend zurück, während die Zeit die online verbracht wird zugenommen hat. [50]', pages: [90], chapters: [4] },
        { text: 'In großen Städten mit dichter Besiedelung ist der Anteil an einsamen Menschen höher, ebenso in extrem abgelegenen Gebieten. [51]', pages: [75,76,12,13], chapters: [1,9] },
        { text: 'Ohne regelmäßige soziale Kontakte können Symptome hitzebedingter Krankheiten unbemerkt bleiben. [55]', pages: [2,3,17], chapters: [1,2] },
        { text: 'Ältere Menschen machen einen Großteil der Bevölkerung aus und können mit Herausforderungen wie dem Verlust von Gesellschaft und sozialer Isolation konfrontiert werden. [56]', pages: [2,3,12,13,17], chapters: [1,2] },
        { text: 'Lebensereignisse wie der Beginn des Ruhestands, das verlassen des Bildungssystems oder der Verlust eines Parters / einer Partnerin können soziale Netzwerke verändern und das Gefühl von Einsamkeit verstärken. [57]', pages: [90], chapters: [4] },
      ],
    },
    {
      title: 'EXTREMWETTER',
      bullets: [
        { text: 'Die immer häufiger auftretenden Extremwetterereignisse haben Auswirkungen auf die Infrastruktur, beispielsweise zum Hochwasserschutz. [58]', pages: [34,35], chapters: [4] },
        { text: 'Durch den Klimawandel verursachte intensivere und häufigere Extremereignisse bringen in Kombination mit einer steigenden Umweltverschmutzung sowohl den Menschen als auch das Ökosystem an seine Anpassungsgrenzen. [22]', pages: [72,73], chapters: [9] },
        { text: 'Da eine wärmere Atmosphäre mehr Wasser speichern kann (pro 1°C etwa 7%) werden Niederschläge stärker und häufiger. So ist mit einem globalen Anstieg des durchschnittlichen Niederschlags von 1-3% zu rechnen, wobei sich die Auswirkungen regional unterscheiden können. [22][59]', pages: [72,73], chapters: [9] },
        { text: 'Der Wassergehalt in der Atmosphäre erhöht sich neben einer verstärkten hitzebedingten Verdunstung auch aufgrund der Veränderung des Verhältnisses von gefrohrenem und flüssigem Wasser. [22]', pages: [72,73], chapters: [9] },
        { text: 'Derartige Prozesse begünstigen Extremereignisse wie Dürren und Überflutungen. [22]', pages: [72,73], chapters: [9] },
      ],
    },
  ],
  sources: [
    { id: 0, text: 'BUND (2025): "Grundwasser in Gefahr: BUND legt Studie zur Wasserknappheit vor", verfügbar unter: https://www.bund.net/themen/aktuelles/detail-aktuelles/news/grundwasser-in-gefahr-bund-legt-studie-zur-wasserknappheit-vor/' },
    { id: 1, text: 'Amparo-Salcedo, M., Pérez-Gimeno, A., Navarro-Pedreño, J. (2025): "Water Security Under Climate Change: Challenges and Solutions Across 43 Countries", Water, 17(5). S.5, verfügbar unter: https://www.mdpi.com/2073-4441/17/5/633' },
    { id: 2, text: 'European Environment Agency (2025): "Water scarcity conditions in Europe", verfügbar unter: https://www.eea.europa.eu/en/analysis/indicators/use-of-freshwater-resources-in-europe-1' },
    { id: 3, text: 'European Commission (2026): "Water scarcity and droughts: Preventing and mitigating water scarcity and droughts in the EU", verfügbar unter: https://environment.ec.europa.eu/topics/water/water-scarcity-and-droughts_en' },
    { id: 4, text: 'Bassen, A. et al. (2024): "Hauptgutachten Wasser in einer aufgeheizten Welt", WBGU - Wissenschaftlicher Beirat der Bundesregierung Globale Umweltveränderungen. S.1, verfügbar unter: https://www.wbgu.de/fileadmin/user_upload/wbgu/publikationen/hauptgutachten/hg2024/pdf/wbgu_hg2024.pdf' },
    { id: 5, text: 'Bassen, A. et al. (2024): "Hauptgutachten Wasser in einer aufgeheizten Welt", WBGU - Wissenschaftlicher Beirat der Bundesregierung Globale Umweltveränderungen. S.5, verfügbar unter: https://www.wbgu.de/fileadmin/user_upload/wbgu/publikationen/hauptgutachten/hg2024/pdf/wbgu_hg2024.pdf' },
    { id: 6, text: 'Bassen, A. et al. (2024): "Hauptgutachten Wasser in einer aufgeheizten Welt", WBGU - Wissenschaftlicher Beirat der Bundesregierung Globale Umweltveränderungen. S.29, verfügbar unter: https://www.wbgu.de/fileadmin/user_upload/wbgu/publikationen/hauptgutachten/hg2024/pdf/wbgu_hg2024.pdf' },
    { id: 7, text: 'Bassen, A. et al. (2024): "Hauptgutachten Wasser in einer aufgeheizten Welt", WBGU - Wissenschaftlicher Beirat der Bundesregierung Globale Umweltveränderungen. S.87, verfügbar unter: https://www.wbgu.de/fileadmin/user_upload/wbgu/publikationen/hauptgutachten/hg2024/pdf/wbgu_hg2024.pdf' },
    { id: 8, text: 'Bassen, A. et al. (2024): "Hauptgutachten Wasser in einer aufgeheizten Welt", WBGU - Wissenschaftlicher Beirat der Bundesregierung Globale Umweltveränderungen. S.75, verfügbar unter: https://www.wbgu.de/fileadmin/user_upload/wbgu/publikationen/hauptgutachten/hg2024/pdf/wbgu_hg2024.pdf' },
    { id: 9, text: 'Bassen, A. et al. (2024): "Hauptgutachten Wasser in einer aufgeheizten Welt", WBGU - Wissenschaftlicher Beirat der Bundesregierung Globale Umweltveränderungen. S.78, verfügbar unter: https://www.wbgu.de/fileadmin/user_upload/wbgu/publikationen/hauptgutachten/hg2024/pdf/wbgu_hg2024.pdf' },
    { id: 10, text: 'Bassen, A. et al. (2024): "Hauptgutachten Wasser in einer aufgeheizten Welt", WBGU - Wissenschaftlicher Beirat der Bundesregierung Globale Umweltveränderungen. S.79, verfügbar unter: https://www.wbgu.de/fileadmin/user_upload/wbgu/publikationen/hauptgutachten/hg2024/pdf/wbgu_hg2024.pdf' },
    { id: 11, text: 'Bassen, A. et al. (2024): "Hauptgutachten Wasser in einer aufgeheizten Welt", WBGU - Wissenschaftlicher Beirat der Bundesregierung Globale Umweltveränderungen. S.80, verfügbar unter: https://www.wbgu.de/fileadmin/user_upload/wbgu/publikationen/hauptgutachten/hg2024/pdf/wbgu_hg2024.pdf' },
    { id: 12, text: 'Bassen, A. et al. (2024): "Hauptgutachten Wasser in einer aufgeheizten Welt", WBGU - Wissenschaftlicher Beirat der Bundesregierung Globale Umweltveränderungen. S.4, verfügbar unter: https://www.wbgu.de/fileadmin/user_upload/wbgu/publikationen/hauptgutachten/hg2024/pdf/wbgu_hg2024.pdf' },
    { id: 13, text: 'Wunsch, A., Liesch, T., Broda, S. (2022): "Deep learning shows declining groundwater levels in Germany until 2100 due to climate change", Nat Commun 13, 1221. S.1, verfügbar unter: https://doi.org/10.1038/s41467-022-28770-2' },
    { id: 14, text: 'Wunsch, A., Liesch, T., Broda, S. (2022): "Deep learning shows declining groundwater levels in Germany until 2100 due to climate change", Nat Commun 13, 1221. S.2, verfügbar unter: https://doi.org/10.1038/s41467-022-28770-2' },
    { id: 15, text: 'Stein, U. et al. (2024): "Auswirkungen des Klimawandels auf die Wasserverfügbarkeit - Anpassung an Trockenheit und Dürre in Deutschland (WADKlim)", Umweltbundesamt, 143/2024. S.73, verfügbar unter: https://www.umweltbundesamt.de/system/files/medien/11850/publikationen/143_2024_texte_wadklim.pdf' },
    { id: 16, text: 'Stein, U. et al. (2024): "Auswirkungen des Klimawandels auf die Wasserverfügbarkeit - Anpassung an Trockenheit und Dürre in Deutschland (WADKlim)", Umweltbundesamt, 143/2024. S.83, verfügbar unter: https://www.umweltbundesamt.de/system/files/medien/11850/publikationen/143_2024_texte_wadklim.pdf' },
    { id: 17, text: 'Stein, U. et al. (2024): "Auswirkungen des Klimawandels auf die Wasserverfügbarkeit - Anpassung an Trockenheit und Dürre in Deutschland (WADKlim)", Umweltbundesamt, 143/2024. S.156, verfügbar unter: https://www.umweltbundesamt.de/system/files/medien/11850/publikationen/143_2024_texte_wadklim.pdf' },
    { id: 18, text: 'Stein, U. et al. (2024): "Auswirkungen des Klimawandels auf die Wasserverfügbarkeit - Anpassung an Trockenheit und Dürre in Deutschland (WADKlim)", Umweltbundesamt, 143/2024. S.158, verfügbar unter: https://www.umweltbundesamt.de/system/files/medien/11850/publikationen/143_2024_texte_wadklim.pdf' },
    { id: 19, text: 'Stein, U. et al. (2024): "Auswirkungen des Klimawandels auf die Wasserverfügbarkeit - Anpassung an Trockenheit und Dürre in Deutschland (WADKlim)", Umweltbundesamt, 143/2024. S.290, verfügbar unter: https://www.umweltbundesamt.de/system/files/medien/11850/publikationen/143_2024_texte_wadklim.pdf' },
    { id: 20, text: 'Bassen, A. et al. (2024): "Hauptgutachten Wasser in einer aufgeheizten Welt", WBGU - Wissenschaftlicher Beirat der Bundesregierung Globale Umweltveränderungen. S.38, verfügbar unter: https://www.wbgu.de/fileadmin/user_upload/wbgu/publikationen/hauptgutachten/hg2024/pdf/wbgu_hg2024.pdf' },
    { id: 21, text: 'Bassen, A. et al. (2024): "Hauptgutachten Wasser in einer aufgeheizten Welt", WBGU - Wissenschaftlicher Beirat der Bundesregierung Globale Umweltveränderungen. S.40, verfügbar unter: https://www.wbgu.de/fileadmin/user_upload/wbgu/publikationen/hauptgutachten/hg2024/pdf/wbgu_hg2024.pdf' },
    { id: 22, text: 'Bassen, A. et al. (2024): "Hauptgutachten Wasser in einer aufgeheizten Welt", WBGU - Wissenschaftlicher Beirat der Bundesregierung Globale Umweltveränderungen. S.66-69, verfügbar unter: https://www.wbgu.de/fileadmin/user_upload/wbgu/publikationen/hauptgutachten/hg2024/pdf/wbgu_hg2024.pdf' },
    { id: 23, text: 'Rezaee, O. (2025): "Klimawandel: Daten zeigen drastischen Schwund der Wasserreserven in Europa", Die Zeit. Verfügbar unter: https://www.zeit.de/wissen/umwelt/2025-11/klimawandel-europa-wasser-grundwasser-duerre-wasserkrise-gxe' },

    //Sources for Wasserknappheit 
    { id: 24, text: 'Bassen, A. et al. (2024): "Hauptgutachten Wasser in einer aufgeheizten Welt", WBGU - Wissenschaftlicher Beirat der Bundesregierung Globale Umweltveränderungen. S.86-87, verfügbar unter: https://www.wbgu.de/fileadmin/user_upload/wbgu/publikationen/hauptgutachten/hg2024/pdf/wbgu_hg2024.pdf' },
    { id: 25, text: 'Stein, U. et al. (2024): "Auswirkungen des Klimawandels auf die Wasserverfügbarkeit - Anpassung an Trockenheit und Dürre in Deutschland (WADKlim)", Umweltbundesamt, 143/2024. S.25, verfügbar unter: https://www.umweltbundesamt.de/system/files/medien/11850/publikationen/143_2024_texte_wadklim.pdf' },
    { id: 26, text: 'Stein, U. et al. (2024): "Auswirkungen des Klimawandels auf die Wasserverfügbarkeit - Anpassung an Trockenheit und Dürre in Deutschland (WADKlim)", Umweltbundesamt, 143/2024. S.44, verfügbar unter: https://www.umweltbundesamt.de/system/files/medien/11850/publikationen/143_2024_texte_wadklim.pdf' },
    { id: 27, text: 'Stein, U. et al. (2024): "Auswirkungen des Klimawandels auf die Wasserverfügbarkeit - Anpassung an Trockenheit und Dürre in Deutschland (WADKlim)", Umweltbundesamt, 143/2024. S.94, verfügbar unter: https://www.umweltbundesamt.de/system/files/medien/11850/publikationen/143_2024_texte_wadklim.pdf' },
    { id: 28, text: 'Bassen, A. et al. (2024): "Hauptgutachten Wasser in einer aufgeheizten Welt", WBGU - Wissenschaftlicher Beirat der Bundesregierung Globale Umweltveränderungen. S.42, verfügbar unter: https://www.wbgu.de/fileadmin/user_upload/wbgu/publikationen/hauptgutachten/hg2024/pdf/wbgu_hg2024.pdf' },
    { id: 29, text: 'Landeshauptstadt Stuttgart - Gesundheitsamt und Amt für Umweltschutz (2025): "Hitzeaktionsplan der Landeshauptstadt Stuttgart", Stadtklima Stuttgart. S.15, verfügbar unter: https://www.stadtklima-stuttgart.de/index.php?klima_kliks_hitzeaktionsplan_stuttgart_2025#:~:text=Download%3A%20Hitzeaktionsplan%20Stuttgart%20Juni%202025%20(pdf%2C%2017%20MB)' },
    { id: 30, text: 'Bassen, A. et al. (2024): "Hauptgutachten Wasser in einer aufgeheizten Welt", WBGU - Wissenschaftlicher Beirat der Bundesregierung Globale Umweltveränderungen. S.30, verfügbar unter: https://www.wbgu.de/fileadmin/user_upload/wbgu/publikationen/hauptgutachten/hg2024/pdf/wbgu_hg2024.pdf' },
    { id: 31, text: 'Stein, U. et al. (2024): "Auswirkungen des Klimawandels auf die Wasserverfügbarkeit - Anpassung an Trockenheit und Dürre in Deutschland (WADKlim)", Umweltbundesamt, 143/2024. S.296, verfügbar unter: https://www.umweltbundesamt.de/system/files/medien/11850/publikationen/143_2024_texte_wadklim.pdf' },
    { id: 32, text: 'Bassen, A. et al. (2024): "Hauptgutachten Wasser in einer aufgeheizten Welt", WBGU - Wissenschaftlicher Beirat der Bundesregierung Globale Umweltveränderungen. S.36, verfügbar unter: https://www.wbgu.de/fileadmin/user_upload/wbgu/publikationen/hauptgutachten/hg2024/pdf/wbgu_hg2024.pdf' },
    { id: 33, text: 'Bundesministerium für Umwelt, Klimaschutz, Naturschutz und nukleare Sicherheit (2025): "Die Deutsche Anpassungsstrategie an den Klimawandel", verfügbar unter: https://www.bundesumweltministerium.de/themen/klimaanpassung/die-deutsche-anpassungsstrategie-an-den-klimawandel' },
    { id: 34, text: 'García-León, D. et al. (2024): "Temperature-related mortality burden and projected change in 1368 European regions: a modelling study", The Lancet Public Health. S.e644, verfügbar unter: https://www.thelancet.com/journals/lanpub/article/PIIS2468-2667(24)00179-8/fulltext' },
    { id: 35, text: 'García-León, D. et al. (2024): "Temperature-related mortality burden and projected change in 1368 European regions: a modelling study", The Lancet Public Health. S.e649, verfügbar unter: https://www.thelancet.com/journals/lanpub/article/PIIS2468-2667(24)00179-8/fulltext' },
    { id: 36, text: 'DWD - Deutscher Wetterdienst (2026): "Klimawandel - ein Überblick", verfügbar unter: https://www.dwd.de/DE/klimaumwelt/klimawandel/klimawandel_node.html' },
    { id: 37, text: 'DWD - Deutscher Wetterdienst, ExtremWetterKongress (2025): "Was wir über das Extremwetter in Deutschland wissen: Stand der Wissenschaft zu Extremwetterereignissen im Klimawandel in Deutschland, Ausgabe 2025", DMG - Deutsche Meteorologische Gesellschaft. S.5, verfügbar unter: https://www.dmg-ev.de/wp-content/uploads/2026/02/faktenpapier_extremwetterkongress.pdf' },
    { id: 38, text: 'DWD - Deutscher Wetterdienst, ExtremWetterKongress (2025): "Was wir über das Extremwetter in Deutschland wissen: Stand der Wissenschaft zu Extremwetterereignissen im Klimawandel in Deutschland, Ausgabe 2025", DMG - Deutsche Meteorologische Gesellschaft. S.7, verfügbar unter: https://www.dmg-ev.de/wp-content/uploads/2026/02/faktenpapier_extremwetterkongress.pdf' },
    { id: 39, text: 'DWD - Deutscher Wetterdienst, ExtremWetterKongress (2025): "Was wir über das Extremwetter in Deutschland wissen: Stand der Wissenschaft zu Extremwetterereignissen im Klimawandel in Deutschland, Ausgabe 2025", DMG - Deutsche Meteorologische Gesellschaft. S.11, verfügbar unter: https://www.dmg-ev.de/wp-content/uploads/2026/02/faktenpapier_extremwetterkongress.pdf' },
    { id: 40, text: 'Beniston, M. et al. (2007): "Future extreme events in European climate: an exploration of regional climate model projections", Climate Change 81 (Suppl1), Springer Nature. S.72, 92, verfügbar unter: https://link.springer.com/article/10.1007/s10584-006-9226-z' },
    { id: 41, text: 'European Climate and Health Observatory, Climate ADAPT (2025): "Heat", verfügbar unter: https://climate-adapt.eea.europa.eu/en/observatory/topics/health-impacts/heat-and-health' },

    //Sources Natur & Boden
    { id: 42, text: 'Bassen, A. et al. (2024): "Hauptgutachten Wasser in einer aufgeheizten Welt", WBGU - Wissenschaftlicher Beirat der Bundesregierung Globale Umweltveränderungen. S.93, verfügbar unter: https://www.wbgu.de/fileadmin/user_upload/wbgu/publikationen/hauptgutachten/hg2024/pdf/wbgu_hg2024.pdf' },
    { id: 43, text: 'Bassen, A. et al. (2024): "Hauptgutachten Wasser in einer aufgeheizten Welt", WBGU - Wissenschaftlicher Beirat der Bundesregierung Globale Umweltveränderungen. S.76, verfügbar unter: https://www.wbgu.de/fileadmin/user_upload/wbgu/publikationen/hauptgutachten/hg2024/pdf/wbgu_hg2024.pdf' },
    { id: 44, text: 'Bassen, A. et al. (2024): "Hauptgutachten Wasser in einer aufgeheizten Welt", WBGU - Wissenschaftlicher Beirat der Bundesregierung Globale Umweltveränderungen. S.90, verfügbar unter: https://www.wbgu.de/fileadmin/user_upload/wbgu/publikationen/hauptgutachten/hg2024/pdf/wbgu_hg2024.pdf' },

    //Urbane Entwicklung
    { id: 45, text: 'Scholten, C. et al. (2025): "The future of water availability and use in the EU: A foresight study and policy options to address water scarcity", European Parliament - Directorate General for Parliamentary Research Services, Panel for the Future of Science and Technology. S.43, verfügbar unter: https://op.europa.eu/en/publication-detail/-/publication/74d5e7d8-19a1-11f0-b1a3-01aa75ed71a1/language-en' },
    { id: 46, text: 'Scholten, C. et al. (2025): "The future of water availability and use in the EU: A foresight study and policy options to address water scarcity", European Parliament - Directorate General for Parliamentary Research Services, Panel for the Future of Science and Technology. S.58, verfügbar unter: https://op.europa.eu/en/publication-detail/-/publication/74d5e7d8-19a1-11f0-b1a3-01aa75ed71a1/language-en' },
    { id: 47, text: 'Ellsworth-Krebs (2020), zit. nach Bagheri, M. et al. (2024): "Implementing housing policies for a sufficient lifestyle", Buildings & Cities, Frauenhofer-Publica. S.301, verfügbar unter: https://publica-rest.fraunhofer.de/server/api/core/bitstreams/27ae97e6-3071-4a7c-bb70-633e79d5fefa/content' },
    { id: 48, text: 'Bierwirth & Thomas (2019), zit.nach Bagheri, M. et al. (2024): "Implementing housing policies for a sufficient lifestyle", Buildings & Cities, Frauenhofer-Publica. S.301, verfügbar unter: https://publica-rest.fraunhofer.de/server/api/core/bitstreams/27ae97e6-3071-4a7c-bb70-633e79d5fefa/content' },

    //Soziale Isolation
    { id: 49, text: 'Schnepf, S. V., d`Hombres, B., Mauri, C. (2024): "Loneliness in Europe: Determinants, Risks and Interventions", Springer Nature. S.3, verfügbar unter: https://link.springer.com/book/10.1007/978-3-031-66582-0' },
    { id: 50, text: 'Schnepf, S. V., d`Hombres, B., Mauri, C. (2024): "Loneliness in Europe: Determinants, Risks and Interventions", Springer Nature. S.93, verfügbar unter: https://link.springer.com/book/10.1007/978-3-031-66582-0' },
    { id: 51, text: 'Schnepf, S. V., d`Hombres, B., Mauri, C. (2024): "Loneliness in Europe: Determinants, Risks and Interventions", Springer Nature. S.51, verfügbar unter: https://link.springer.com/book/10.1007/978-3-031-66582-0' },

    // Urbane Entwicklung
    { id: 52, text: 'Destatis - Statistisches Bundesamt (2026): "Bevölkerung - Großstadtregionen im Wandel", verfügbar unter: http://destatis.de/DE/Themen/Querschnitt/Demografischer-Wandel/Aspekte/demografie-grossstadtregionen.html' },
    { id: 53, text: 'Bassen, A. et al. (2024): "Hauptgutachten Wasser in einer aufgeheizten Welt", WBGU - Wissenschaftlicher Beirat der Bundesregierung Globale Umweltveränderungen. S.91, verfügbar unter: https://www.wbgu.de/fileadmin/user_upload/wbgu/publikationen/hauptgutachten/hg2024/pdf/wbgu_hg2024.pdf' },
    { id: 54, text: 'Klima Campus (2026): "City Life 2050: Was bedeutet nachhaltige Stadtentwicklung?", mycelia gGmbH, verfügbar unter: https://klimacampus.org/city-life-2050-die-zukunft-beginnt-jetzt/' },
    
    //Soziale Isolation
    { id: 55, text: 'Landeshauptstadt Stuttgart - Gesundheitsamt und Amt für Umweltschutz (2025): "Hitzeaktionsplan der Landeshauptstadt Stuttgart", Stadtklima Stuttgart. S.15, verfügbar unter: https://www.stadtklima-stuttgart.de/index.php?klima_kliks_hitzeaktionsplan_stuttgart_2025#:~:text=Download%3A%20Hitzeaktionsplan%20Stuttgart%20Juni%202025%20(pdf%2C%2017%20MB)' },
    { id: 56, text: 'Schnepf, S. V., d`Hombres, B., Mauri, C. (2024): "Loneliness in Europe: Determinants, Risks and Interventions", Springer Nature. S.4, verfügbar unter: https://link.springer.com/book/10.1007/978-3-031-66582-0' },
    { id: 57, text: 'Schnepf, S. V., d`Hombres, B., Mauri, C. (2024): "Loneliness in Europe: Determinants, Risks and Interventions", Springer Nature. S.44, 57, verfügbar unter: https://link.springer.com/book/10.1007/978-3-031-66582-0' },
    
    //Extremwetter
    { id: 58, text: 'Bassen, A. et al. (2024): "Hauptgutachten Wasser in einer aufgeheizten Welt", WBGU - Wissenschaftlicher Beirat der Bundesregierung Globale Umweltveränderungen. S.74, verfügbar unter: https://www.wbgu.de/fileadmin/user_upload/wbgu/publikationen/hauptgutachten/hg2024/pdf/wbgu_hg2024.pdf' },
    { id: 59, text: 'Bassen, A. et al. (2024): "Hauptgutachten Wasser in einer aufgeheizten Welt", WBGU - Wissenschaftlicher Beirat der Bundesregierung Globale Umweltveränderungen. S.35, verfügbar unter: https://www.wbgu.de/fileadmin/user_upload/wbgu/publikationen/hauptgutachten/hg2024/pdf/wbgu_hg2024.pdf' },



  ],
};

export default content;
