import { BookContent } from './types';

const content: BookContent = {
  bookId: 4,
  keyPoints: [
    { text: 'In Stuttgart ist eine Verdopplung der von Hitze belasteten Tage bis Mitte des Jahrhunderts möglich. [1]', pages: [], chapters: [] },
    { text: 'Deutschland erwärmt sich, verglichen mit der Vorindustriellen Zeit bisher um 2,5°C und damit doppelt so schnell wie der globale Durchschnitt. [7]', pages: [], chapters: [] },
    { text: 'Hitze verursacht die höchsten Todeszahlen aller Extremereignisse in Deutschland. [7]', pages: [], chapters: [] },
    { text: 'Ein Hitzeschlag bei dem die Körpertemperatur > 40°C beträgt kann zu Organversagen führen. [3]', pages: [], chapters: [] },
    { text: 'Naturbasierte Lösungen in der Raumplanung (Feuchtgebiete, grüne Pufferzonen, ...) verbessern die Wasserrückhaltung, Bodengesundheit und Biodiviersität. Außerdem verringern sie städtische Hitze. [29][30]', pages: [], chapters: [] },
  ],
  sections: [
    {
      title: 'ZUR WELT IN DIE OASE',
      bullets: [
        { text: 'Europa erwärmt sich mit fast 1°C stärker als der weltweite durchschnitt und ist somit der Kontinent mit der stärksten Erwärmung. [12]', pages: [], chapters: [] },
        { text: 'Bis Ende des 21. Jahrhunderts werden mitteleuropäische Länder dieselbe Anzahl an heißen Tagen verzeichnen wie derzeit Südeuropa. [13]', pages: [], chapters: [] },
        { text: 'Stuttgart wird sich in Sommermonaten stärker aufheizen: Bis Mitte des Jahrhunderts kann es zu einer Verdopplung der Tage mit starker Wärmebelastung kommmen. [1]', pages: [], chapters: [] },
        { text: 'Besonders Industrie- und Gewerbegebiete sowie dicht bebaute Stadtteile mit hoher Versiegelung sind betroffen. Hier kann es bis zu mehr als 35 Belastungstagen pro Jahr kommen. [1]', pages: [], chapters: [] },
        { text: 'Derzeit verzeihnet die Stuttgarter Innenstadt durchschnittlich 30 heiße Tage pro Jahr. Eine Erwärmung um 3°C könnte zu einem Anstieg aufüber 70 Tagen führen. [2]', pages: [], chapters: [] },
        { text: 'Tropische Nächte (per Definition ≥ 20°C) nehmen zu und stellen eine ernsthafte Gefahr für die Gesundheit dar, da mehrere Tage anhaltende Hitze ohne nächtliche Abkühlung den Hitzestress verstärken. [2]', pages: [], chapters: [] },
        { text: 'Gebäude und Asphalt speichern tagsüber Wärme und geben sie nachts ab. Daher kühlen Städte wesentlich langsamer ab. Faktoren wie dichte Bebauung, Versiegelung und Mangel an Grünflächen verschärfen den Effekt. [6]', pages: [], chapters: [] },
        { text: 'Die Dauer der stärksten Hitzewellen lag 1971-2000 im Mittel bei 4,3 Tagen. Eine globale Erwärmung um 3°C würde eine Zunahme auf bis zu 7,5 Tagen bededuten. [2]', pages: [], chapters: [] },
        { text: 'Gesundheitliche Auswirkungen durch Hitze können sich durch Dehydrierung, Hitzeschlag (mit teils tödlichem Verlauf) oder Hitzeerschöpfung in Form von Schwäche, Schwindel und Kreislaufproblemen äußern. Außerdem wird das Unfallrisiko aufgrund verminderter Konzentrationsfähigkeit erhöht. [3]', pages: [], chapters: [] },
        { text: 'Stuttgart plant bedarfsorientierte Verdichtung von Trinkwassermöglichkeiten sowie eine interaktive Karte, die Trinkwasserbrunnen und kühle Orte aufzeigt. [4]', pages: [7], chapters: [1] },
        { text: 'Hitzeschutzmaßnahmen: Sonnenbeschienene Räume tagsüber mit Vorhängen abdunkeln. Nur Nachts und morgens Lüften, solange die Außentemperatur niedriger ist als die Wohnungstemperatur. [5]', pages: [], chapters: [] },
        { text: 'Deutschland erwärmt sich, verglichen mit der Vorindustriellen Zeit bisher um 2,5°C und damit doppelt so schnell wie der globale Durchschnitt. Dieser Trend beschleunigt sich in den letzten 50 Jahren [7]', pages: [], chapters: [] },
        { text: 'Hitze verursacht die höchsten Todeszahlen aller Extremereignisse in Deutschland. [7]', pages: [], chapters: [] },
        { text: 'Bei ungebremstem Treibhausgasausstoß werden zwischen 2031 und 2060 fünf bis 20 weitere heiße Tage pro Jahr in Süddeutschland erwartet. [7]', pages: [], chapters: [] },
        { text: 'Besonders hitzevulnerabel sind ältere Menschen aufgrund einer verminderten Fähigkeit der Temperaturregulation (Schwitzen), einem reduzierten Durstempfinden sowie einem anfälligeren Herz-Kreislauf-System. [8]', pages: [], chapters: [] },
        { text: 'Die Zahl der Todesfälle ist bei Menschen ab 85 Jahren am höchsten. [9]', pages: [], chapters: [] },
        { text: 'Dachgeschosswohnungen unter direkter Sonneneinstrahlung heizen sich schnell auf und verfügen häufig nicht über ausreichende Kühlmöglichkeiten. [10]', pages: [], chapters: [] },
        { text: 'Ein fehlendes soziales Netz kann dazu führen, dass Symptome hitzebedingter Erkrankungen unbemerkt bleiben, bis sie ernsthafte Gesundheitsrisiken darstellen. [10]', pages: [], chapters: [] },
        { text: 'Steigende Temperaturen erhöhen des Trinkwassergrundbedarf. Eine Ausreichende Versorgung mit Wasser ist daher essenziell für Hitzeschutz. Gleichzeitig sorgen Hitzewellen für Versorgungsengpässe. [11]', pages: [], chapters: [] },
        { text: 'Städte entwickeln Hitzeschutzpläne mit Kühlzentren, Karten kühler Orte und öffentlich kommunizierten Trinkwasserstellen als institutionalisierte Reaktion auf Extremhitze. [14]', pages: [], chapters: [] },
        { text: 'In jedem zweiten Landkreis in Deutschland herrscht bereits Wasserstress. Grundwasserspiegel sinken, Böden trocknen aus und in einigen Landkreisen gab es bereits Engpässe bei der Trinkwasserversorgung. [25]', pages: [], chapters: [] },
        { text: 'In Süddeutschland (Bayern und Baden-Württemberg) sind einzelne Regionen bereits von Grundwasserstress betroffen. [25]', pages: [], chapters: [] },
        { text: 'Naturbasierte Lösungen in der Raumplanung (Feuchtgebiete, grüne Pufferzonen, ...) verbessern die Wasserrückhaltung, Bodengesundheit und Biodiviersität. Außerdem verringern sie städtische Hitze. [29][30]', pages: [], chapters: [] },
        { text: 'Moderne Technologien können Wassermanagement revolutionieren. [29]', pages: [88, 89, 90, 91, 92], chapters: [8] },
        { text: 'Intelligente Bewässerungssysteme nutzen Bodenfeuchtesensoren und Wetterdaten um den Wasserverbrauch zu optimieren. [31]', pages: [97], chapters: [9] },
      ],
    },
    {
      title: 'HITZE',
      bullets: [
        { text: 'Die heißen Tage in Stuttgart pro Jahr belaufen sich aktuell auf 30, könnten aber in Zukunft bei einer Erwärmung um 3°C auf über 70 ansteigen. Auch die Nächte kühlen immer weniger ab. [2]', pages: [1], chapters: [1] },
        { text: 'Gebäude, Beton und Asphalt speichern tagsüber Wärme und geben sich nachts ab, weshalb städtische Gebiete wesentlich langsamer abkühlen. Das wird auch städtische Wärmeinsel genannt. [6]', pages: [3, 49], chapters: [1, 4] },
        { text: 'In Deutschland sind langanhaltende Phasen mit Tageshöchsttemperaturen von 30°C und darüber kein neues Phänomen. Dieser Trend verschärft sich weiter. [15]', pages: [5], chapters: [1] },
        { text: 'Dachgeschosswohnungen heizen sich unter direkter Sonneneinstrahlung schnell auf und verfügen häufig über unzureichende Kühlmöglichkeiten. [10]', pages: [6], chapters: [1] },
        { text: 'In Stuttgart ist eine Verdopplung der von Hitze belasteten Tage bis Mitte des Jahrhunderts möglich. [1]', pages: [7], chapters: [1] },
        { text: 'Institutionalisierte Hitzeschutzpläne werden bereits entwickelt. [14]', pages: [7], chapters: [1] },
        { text: 'Bis 2060 kann es bei ungebremstem Treibhausgasausstoß zu einer Zunahme von 10 bis 20 heißen Tagen pro Jahr in Süddeutschland kommen. [7]', pages: [10], chapters: [1] },
        { text: 'Die stärkste Hitzebelastung erfahren dicht bebaute Stadtregionen mit hohem Versieglungsanteil. Gebäudeformen die wenig Schatten spenden verstärken den Effekt zusätzlich. [1]', pages: [17, 18, 19, 20], chapters: [2] },
        { text: 'Extreme Hitze kann zur sog. Hitzeerschöpfung führen (Schwäche, Schwindel, Kreislaufprobleme). [3]', pages: [47, 48, 49, 50, 51, 52, 53], chapters: [4] },
        { text: 'Durch Dehydration werden die Körperfunktionen stark beeinträchtigt. [3]', pages: [47, 48, 49, 50, 51, 52, 53], chapters: [4] },
        { text: 'Ein Hitzeschlag bei dem die Körpertemperatur > 40°C beträgt kann zu Organversagen führen. [3]', pages: [47, 48, 49, 50, 51, 52, 53], chapters: [4] },
        { text: 'Weitere häufige, hitzebedingte Erkrankungen sind Sonnenbrand und Sonnenstich, die durch direkte Sonnenexposition ohne Schutz entstehen. [3]', pages: [60], chapters: [5] },
        { text: 'Grüne Infrastruktur (z.B. Pflanzenwände, Dachgärten, ...) mildern den sog. Wärmeinsel-Effekt, da Pflanzen durch die Verdunstung kühlend wirken. [6][16]', pages: [72, 73], chapters: [6] },
        { text: 'Klimaresilienz erfordert flexible, ineinandergreifende und robuste Maßnahmen. [17]', pages: [101], chapters: [9] },
      ],
    },
    {
      title: 'WASSERKNAPPHEIT',
      bullets: [
        { text: 'In der EU waren 2023 etwa 28% der Landfläche von saisonaler Wasserknappheit betroffen. Es ist unwahrscheinlich, dass sich diese Verknapphung bis 2030 verringern wird. [18]', pages: [7], chapters: [1] },
        { text: 'Ausgeprägte Hitzewellen führen zu höheren Tagesspitzenverbräuchen von Wasser. Dadurch werden Aufbereitungsanlagen und Verteilungsnetze belastet, deren Kapazität möglicherweise nicht ausreicht. Daraus können wiederum temporäre Versorgungsengpässe resultieren. [19]', pages: [7], chapters: [1] },
        { text: 'Bodenvedrsiegelung, Grundwasserübernutzung und steigende Wassernachfrage durch Verstädterung sind Haupttreiber für urbanen Wassermangel. [20]', pages: [35], chapters: [3] },
        { text: 'Bisher sind mehr als 933 Mio. Menschen von Wasserknappheit in Städten betroffen. Diese Zahl könnte bis 2050 auf 1,6 bis 2,3 Mrd. ansteigen. [20]', pages: [35], chapters: [3] },
        { text: 'Wasserknappheitskrisen gehen häufig nicht auf fehlende Verfügbarkeit, sondern auf ungleiche Verteilung zurück. [21]', pages: [50], chapters: [4] },
        { text: 'Sinkende Grundwasserspiegel zwangen Wasserversorger bereits in Trockenperioden zur maximalen Kapazitätsauslastung, wodurch lokale Versorgungsengpässe entstanden. [22]', pages: [50], chapters: [4] },
        { text: 'Langanhaltende Dürreperioden führen zum Versiegen von Quellwasserverschüttungen und dem Absenken von Grundwasserständen. Dadruch wird die Trinkwasserbereitstellung gefährdet. [19]', pages: [55], chapters: [4] },
        { text: 'Der Klimawandel verschärft saisonale Schwankungen der Süßwasserverfügbarkeit, während Dürreereignisse and Intensität und Häufigkeit zunehmen. [18]', pages: [55], chapters: [4] },
        { text: 'Eine zunehmende Flächenversiegelung erhöt die Gefahr von schnellen Abflüssen da versiegelter Boden kein Wasser aufnehmen kann. [23]', pages: [59], chapters: [5] },
        { text: 'Der Klimawandel und die Wasserverschmutzung werden ohne wirksame Gegenmaßnahmen die ausreichende Versorgung von Wasser gefährden. [24]', pages: [97], chapters: [9] },
        { text: 'Bis 2050 könnte die Zahl der Menschen in Städten mit Wasserknappheit auf bis zu 2,3 Mrd. ansteigen. Das entspricht etwa einem Drittel bis fast die Hälfte der globalen Stadtbevölkerung. [20]', pages: [105], chapters: [9] },
      ],
    },
    {
      title: 'URBANE ENTWICKLUNG',
      bullets: [
        { text: 'Investitionen in grüne Infrastruktur (Gründächer, Stadtwälder, durchlässige Pflasterungen) verbessern die städtische Resilienz, die Wasserrückhaltung und verringern Hitzeinsel-Effekte. [26]', pages: [5, 6], chapters: [1] },
        { text: 'Die Veränderung der Landnutzung bedroht Biodiviersität und beeinträchtig die Ökosystemproduktivität durch Habitatverluste und Bodenversiegelung. [27]', pages: [17, 18, 19, 20], chapters: [2] },
        { text: 'Städte sollen widerstandsfähiger gegen Klimawandel und Naturkatastrophen werden. Die Kombination grauer und grüner Infrastruktur stärkt die Widerstandsfähigkeit. [28][26]', pages: [75, 76, 77 ,78, 79, 80, 81, 82, 83, 84 ,85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95], chapters: [6, 7, 8] },
        { text: 'Mit steigender Bevölkerungszahl stehen Städte vor dedr Aufgabe, Wachstum udn Lebensqualität in Einklang zu bringen. [36]', pages: [], chapters: [] },
      ],
    },
    {
      title: 'SOZIALE ISOLATION',
      bullets: [
        { text: 'Die Digitalisierung verändert die soziale Interaktion: Persönliche Kommunikation nimmt ab, während die online verbrachte Zeit dramatisch zunimmt. [32]', pages: [6, 15, 99], chapters: [1, 2, 9] },
        { text: 'Einsamkeit hat sich zu einer "Epidemie des 21. Jahrhunderts" entwickelt. [33]', pages: [6], chapters: [1] },
        { text: 'Junge Erwachsene sind häufiger von Einsamkeit betroffen als Erwachsene mittleren und höheren Alters. [34]', pages: [35, 36], chapters: [3] },
        { text: 'Einsamkeit nimmt in großen, die besiedelten Gegenden zu. [35]', pages: [6, 68], chapters: [1, 5] },
      ],
    },  
    {
      title: 'EXTREMWETTER',
      bullets: [
        { text: 'Der fortschreitende Klimawandel verursacht Extremereignisse, deren Intensität und Häufigkeit über bisherige Erfahrungen hinausgehen. Die Grenzen der Anpassungsfähigkeit von Mensch und Natur werden zunehmend überschritten. [37]', pages: [48, 49, 50, 51, 52, 53], chapters: [4] },
        { text: 'Wetterextreme werden häufiger und heftiger. Stürme, Starkregen, Hochwasser, Dürre und Hitze sind keine Jahrhundertereignisse mehr, sondern Teil einer neuen Realität. [38]', pages: [7, 8], chapters: [1] },
      ],
    },
  ],
  sources: [
    { id: 1, text: 'DWD - Deutscher Wetterdienst (2017): "Stuttgart - Klimawandel im Kessel: künftig mehr Tage mit starker Wärmebelastung", verfügbar unter: https://www.dwd.de/DE/klimaumwelt/aktuelle_meldungen/170614/stadtklima_stuttgart_waermebelastung.html' },
    { id: 2, text: 'Landeshauptstadt Stuttgart - Gesundheitsamt und Amt für Umweltschutz (2025): "Hitzeaktionsplan der Landeshauptstadt Stuttgart", Stadtklima Stuttgart. S. 10-11, verfügbar unter: https://www.stadtklima-stuttgart.de/index.php?klima_kliks_hitzeaktionsplan_stuttgart_2025' },
    { id: 3, text: 'Landeshauptstadt Stuttgart - Gesundheitsamt und Amt für Umweltschutz (2025): "Hitzeaktionsplan der Landeshauptstadt Stuttgart", Stadtklima Stuttgart. S. 15, verfügbar unter: https://www.stadtklima-stuttgart.de/index.php?klima_kliks_hitzeaktionsplan_stuttgart_2025' },
    { id: 4, text: 'Landeshauptstadt Stuttgart - Gesundheitsamt und Amt für Umweltschutz (2025): "Hitzeaktionsplan der Landeshauptstadt Stuttgart", Stadtklima Stuttgart. S. 44, 64, 66, verfügbar unter: https://www.stadtklima-stuttgart.de/index.php?klima_kliks_hitzeaktionsplan_stuttgart_2025' },
    { id: 5, text: 'Bundesministerium für Umwelt, Klimaschutz, Naturschutz und nukleare Sicherheit (2025): "Extremwetterereignisse", verfügbar unter: https://www.bundesumweltministerium.de/themen/gesundheit/gesundheit-im-klimawandel/extremwetterereignisse/ueberblick-extremwetterereignisse' },
    { id: 6, text: 'DWD - Deutscher Wetterdienst (2025): "Was wir über das Extremwetter in Deutschland wissen: Stand der Wissenschaft zu Extremwetterereignissen im Klimawandel in Deutschland, Ausgabe 2025", DMG - Deutsche Meteorologische Gesellschaft. S. 11, verfügbar unter: https://www.dmg-ev.de/wp-content/uploads/2026/02/faktenpapier_extremwetterkongress.pdf' },
    { id: 7, text: 'DWD - Deutscher Wetterdienst (2025): "Was wir über das Extremwetter in Deutschland wissen: Stand der Wissenschaft zu Extremwetterereignissen im Klimawandel in Deutschland, Ausgabe 2025", DMG - Deutsche Meteorologische Gesellschaft. S. 5-8, verfügbar unter: https://www.dmg-ev.de/wp-content/uploads/2026/02/faktenpapier_extremwetterkongress.pdf' },
    { id: 8, text: 'Landeshauptstadt Stuttgart - Gesundheitsamt und Amt für Umweltschutz (2025): "Hitzeaktionsplan der Landeshauptstadt Stuttgart", Stadtklima Stuttgart. S. 16, verfügbar unter: https://www.stadtklima-stuttgart.de/index.php?klima_kliks_hitzeaktionsplan_stuttgart_2025' },
    { id: 9, text: 'García-León, D. et al. (2024): "Temperature-related mortality burden and projected changes in 1368 European regions: a modelling study", The Lancet Public Health. S. e649, verfügbar unter: https://www.thelancet.com/journals/lanpub/article/PIIS2468-2667(24)00179-8/fulltext' },
    { id: 10, text: 'Landeshauptstadt Stuttgart - Gesundheitsamt und Amt für Umweltschutz (2025): "Hitzeaktionsplan der Landeshauptstadt Stuttgart", Stadtklima Stuttgart. S. 17-18, verfügbar unter: https://www.stadtklima-stuttgart.de/index.php?klima_kliks_hitzeaktionsplan_stuttgart_2025' },
    { id: 11, text: 'Bassen, A. et al. (2024): "Hauptgutachten Wasser in einer aufgeheizten Welt", WBGU - Wissenschaftlicher Beirat der Bundesregierung Globale Umweltveränderungen. S. 92, 75, verfügbar unter: https://www.wbgu.de/fileadmin/user_upload/wbgu/publikationen/hauptgutachten/hg2024/pdf/wbgu_hg2024.pdf' },
    { id: 12, text: 'Ballester, J. et al. (2023): "Heat-related mortality in Europe during the summer of 2022", Nature Medicine (29). S. 1857, verfügbar unter: https://www.nature.com/articles/s41591-023-02419-z' },
    { id: 13, text: 'Beniston, M. et al. (2007): "Future extreme events in European climate: an exploration of regional model projections", Climatic Change 81 (Suppl1), Springer Nature Link. S. 72, verfügbar unter: https://link.springer.com/article/10.1007/s10584-006-9226-z' },
    { id: 14, text: 'Landeshauptstadt Stuttgart - Gesundheitsamt und Amt für Umweltschutz (2025): "Hitzeaktionsplan der Landeshauptstadt Stuttgart", Stadtklima Stuttgart. S. 10,72, verfügbar unter: https://www.stadtklima-stuttgart.de/index.php?klima_kliks_hitzeaktionsplan_stuttgart_2025' },
    { id: 15, text: 'DWD - Deutscher Wetterdienst (2025): "Was wir über das Extremwetter in Deutschland wissen: Stand der Wissenschaft zu Extremwetterereignissen im Klimawandel in Deutschland, Ausgabe 2025", DMG - Deutsche Meteorologische Gesellschaft. S. 4, verfügbar unter: https://www.dmg-ev.de/wp-content/uploads/2026/02/faktenpapier_extremwetterkongress.pdf' },
    { id: 16, text: 'Dahal, D. et al. (2025): "A Review on Climate Change Impacts on Freshwater Systems and Ecosystem Resilience", Water 2025, 17(21), MDPI. S. 17, verfügbar unter: https://www.mdpi.com/2073-4441/17/21/3052' },
    { id: 17, text: 'Umweltbundesamt (2022): "Extreme Events / Climate Change", verfügbar unter: https://www.umweltbundesamt.de/en/topics/water/extreme-events-climate-change' },
    { id: 18, text: 'European Environment Agency (2025): "Water scarcity conditions in Europe", verfügbar unter: https://www.eea.europa.eu/en/analysis/indicators/use-of-freshwater-resources-in-europe-1' },
    { id: 19, text: 'Bassen, A. et al. (2024): "Hauptgutachten Wasser in einer aufgeheizten Welt", WBGU - Wissenschaftlicher Beirat der Bundesregierung Globale Umweltveränderungen. S. 75, verfügbar unter: https://www.wbgu.de/fileadmin/user_upload/wbgu/publikationen/hauptgutachten/hg2024/pdf/wbgu_hg2024.pdf' },
    { id: 20, text: 'Bassen, A. et al. (2024): "Hauptgutachten Wasser in einer aufgeheizten Welt", WBGU - Wissenschaftlicher Beirat der Bundesregierung Globale Umweltveränderungen. S. 6, verfügbar unter: https://www.wbgu.de/fileadmin/user_upload/wbgu/publikationen/hauptgutachten/hg2024/pdf/wbgu_hg2024.pdf' },
    { id: 21, text: 'Bassen, A. et al. (2024): "Hauptgutachten Wasser in einer aufgeheizten Welt", WBGU - Wissenschaftlicher Beirat der Bundesregierung Globale Umweltveränderungen. S. 5, 86, verfügbar unter: https://www.wbgu.de/fileadmin/user_upload/wbgu/publikationen/hauptgutachten/hg2024/pdf/wbgu_hg2024.pdf' },
    { id: 22, text: 'Wunsch, A., Liesch, T., Broda, S. (2022): "Deep learning shows declining groundwater levels in Germany until 2100 due to climate change", Nat Commun 13,1221. S. 2, verfügbar unter: https://www.nature.com/articles/s41467-022-28770-2' },
    { id: 23, text: 'Bassen, A. et al. (2024): "Hauptgutachten Wasser in einer aufgeheizten Welt", WBGU - Wissenschaftlicher Beirat der Bundesregierung Globale Umweltveränderungen. S. 38, verfügbar unter: https://www.wbgu.de/fileadmin/user_upload/wbgu/publikationen/hauptgutachten/hg2024/pdf/wbgu_hg2024.pdf' },
    { id: 24, text: 'Bassen, A. et al. (2024): "Hauptgutachten Wasser in einer aufgeheizten Welt", WBGU - Wissenschaftlicher Beirat der Bundesregierung Globale Umweltveränderungen. S. 66, verfügbar unter: https://www.wbgu.de/fileadmin/user_upload/wbgu/publikationen/hauptgutachten/hg2024/pdf/wbgu_hg2024.pdf' },
    { id: 25, text: 'BUND (2025): "Grundwasser in Gefahr: BUND legt Studie zur Wasserknappheit vor", verfügbar unter: https://www.bund.net/themen/aktuelles/detail-aktuelles/news/grundwasser-in-gefahr-bund-legt-studie-zur-wasserknappheit-vor/' },
    { id: 26, text: 'Dahal, D. et al. (2025): "A Review on Climate Change Impacts on Freshwater Systems and Ecosystem Resilience", Water 2025, 17(21), MDPI. S. 16-17, verfügbar unter: https://www.mdpi.com/2073-4441/17/21/3052' },
    { id: 27, text: 'Seto, K.C., Güneralp, B., Hutyra, L.R. (2012): "Global forecasts of urban expansion to 2030 and direct impacts on biodiversity and carbon pools", PNAS. S. 16083, verfügbar unter: https://www.pnas.org/doi/full/10.1073/pnas.1211658109' },
    { id: 28, text: 'Klima Campus (2026): "City Life 2050: Was bededutet nachhaltige Stadtentwicklung?", mycelia gGmbH, verfügbar unter: https://klimacampus.org/city-life-2050-die-zukunft-beginnt-jetzt/' },
    { id: 29, text: 'Europäisches Parlement (2025): "Europas Gewässer: Herausforderungen und Lösungsansätze der EU", verfügbar unter: https://www.europarl.europa.eu/topics/de/article/20250428STO28142/europas-gewasser-herausforderungen-und-losungsansatze-der-eu' },
    { id: 30, text: 'Scholten, C. et al. (2025): "The future of water availability and use in the EU: A foresight study and policy options to addresswater scarcity", European Parliament - Directorate General for Parliamentary Research Services, Panel for the Future of Science and Technology. S. 50, verfügbar unter: https://op.europa.eu/en/publication-detail/-/publication/74d5e7d8-19a1-11f0-b1a3-01aa75ed71a1/language-en' },
    { id: 31, text: 'Scholten, C. et al. (2025): "The future of water availability and use in the EU: A foresight study and policy options to addresswater scarcity", European Parliament - Directorate General for Parliamentary Research Services, Panel for the Future of Science and Technology. S. 46, verfügbar unter: https://op.europa.eu/en/publication-detail/-/publication/74d5e7d8-19a1-11f0-b1a3-01aa75ed71a1/language-en' },
    { id: 32, text: 'Schnepf, S.V., d`Hombres, B., Mauri, C. (2024): "Loneliness in Europe: Determinants, Risks and Interventions", Springer Nature. S. 4, 93, verfügbar unter: https://link.springer.com/book/10.1007/978-3-031-66582-0' },
    { id: 33, text: 'Schnepf, S.V., d`Hombres, B., Mauri, C. (2024): "Loneliness in Europe: Determinants, Risks and Interventions", Springer Nature. S. 3-4, verfügbar unter: https://link.springer.com/book/10.1007/978-3-031-66582-0' },
    { id: 34, text: 'Schnepf, S.V., d`Hombres, B., Mauri, C. (2024): "Loneliness in Europe: Determinants, Risks and Interventions", Springer Nature. S. 171, verfügbar unter: https://link.springer.com/book/10.1007/978-3-031-66582-0' },
    { id: 35, text: 'Schnepf, S.V.. d`Hombres, B., Mauri, C. (2024): "Loneliness in Europe: Determinants, Risks and Interventions", Springer Nature. S. 51, verfügbar unter: https://link.springer.com/book/10.1007/978-3-031-66582-0' },
    { id: 36, text: 'ZukunftsInstitut (2025): "Megatrend Urbanisierung", verfügbar unter: https://www.zukunftsinstitut.de/zukunftsthemen/megatrend-urbanisierung' },
    { id: 37, text: 'Bassen, A. et al. (2024): "Hauptgutachten Wasser in einer aufgeheizten Welt", WBGU - Wissenschaftlicher Beirat der Bundesregierung Globale Umweltveränderungen. S. 65, verfügbar unter: https://www.wbgu.de/fileadmin/user_upload/wbgu/publikationen/hauptgutachten/hg2024/pdf/wbgu_hg2024.pdf' },
    { id: 38, text: 'Bundesministerium für Umwelt, Klimaschutz, Naturschutz und nukleare Sicherheit (2025): "Die Deutsche Anpassungsstrategie an den Klimawandel", verfügbar unter: https://www.bundesumweltministerium.de/themen/klimaanpassung/die-deutsche-anpassungsstrategie-an-den-klimawandel' },
  ],
};

export default content;
