import { BookContent } from './types';

const content: BookContent = {
  bookId: 1,
  keyPoints: [
    { text: '. [1]', pages: [12], chapters: [1] },
    { text: '. [2]', pages: [34], chapters: [2] },
    { text: '. [1]', pages: [58], chapters: [3] },
    { text: '. [3]', pages: [82], chapters: [4] },
    { text: '. [2]', pages: [110], chapters: [5] },
  ],
  sections: [
    {
      title: 'DIE WELT DES FAHRWASSERS',
      bullets: [
        { text: 'Wasser wird in Deutschland zunehmend knapp. Jeder zweite Landkreis ist von Wasserstress betroffen (v.A. Lankreise mit intensiver Landwirtschaft, Industrie oder dichter Besiedelung.) [0]', pages: [], chapters: [] },
        { text: 'Wasserknappheit gilt als größte Herausforderung in der Wasserversorgungssicherheit. [1]', pages: [], chapters: [] },
        { text: '28% der EU waren 2023 von Wasserknappheit betroffen. [2]', pages: [], chapters: [] },
        { text: '2023 waren insbesondere Flussteilgebiete von Wasserknappheit betroffen, auch in Deutschland. [2]', pages: [], chapters: [] },
        { text: 'Wasserknappheit betrifft nicht nur Südeuropa sondern die gesamte EU. [2]', pages: [], chapters: [] },
        { text: 'Während der letzten zehn Jahren hat die Häufigkeit und Schwere von Dürren zugenommen, was negative Folgen für die Wasserverfügbarkeit hat. [2]', pages: [], chapters: [] },
        { text: 'Wasserknappheit und Dürren werden in der EU immmer häufiger und flächendeckender. [3]', pages: [], chapters: [] },
        { text: 'Die Herausforderungen um Wasserknappheit verschärfen sich, Unsicherheit wird Normalität und die Anpassungsfähigkeit könnte überschritten werden. [4]', pages: [], chapters: [] },
        { text: 'In heutigen Städten sind mehr als 933 Millionen Menschen von Wasserknappheit betroffen. [5]', pages: [], chapters: [] },
        { text: '2050 werden 30-50% der Weltbevökerung von Wasserknappheit in Städten betroffen sein. [5]', pages: [], chapters: [] },
        { text: 'Die urbane Wassernachfrage wächst bis 2050 um 80%. [5]', pages: [], chapters: [] },
        { text: 'Gründe für urbanen Wassermangel sind: Mangel an Oberflächenwasser, Bodenversiegelung, Grundwasserübernutzung sowie höherer Wasserbedarf aufgrund von Urbanisierung und steigendem Pro-Kopf-Verbrauch. [5]', pages: [], chapters: [] },
        { text: '2050 könnten 1,6 bis 2,3 Mrd. Menschen von Wasserknappheit betroffen sein. [5]', pages: [], chapters: [] },
        { text: 'Der Mensch verteilt Wasser ungerecht und verschmutzt und übernutzt es vielerorts. [6]', pages: [], chapters: [] },
        { text: 'Die ungleiche Verteilung von Wasser äußert sich in der Übernutzung der Wasserressourcen, z.B. durch einkommensstarke Bevölkerungsgruppen im urbanen Raum. [7]', pages: [], chapters: [] },
        { text: 'Schon heute sind die Auswirkungen des Klimawandels auf die Wasserversorgung spürbar. [6]', pages: [], chapters: [] },
        { text: 'Weltweit haben etwa 2,2 Mrd. Menschen keinen Zugang zu sauberem Trinkwasser, insbesondere in ländlichen Gebieten. [6]', pages: [], chapters: [] },
        { text: 'Etwa 3,5 Mrd. Menschen verfügen über keinen ausreichenden Zugang zu sanitären Einrichtungen. [6]', pages: [], chapters: [] },
        { text: 'Stärekere Hitzewellen maximieren den täglichen Wasserverbrauch, was die Kapazität von Aufbereitungsanlagen und Verteilsystemen überlastet. Die Konsequenz sind vorübergehende Versorgungsengpässe und möglicherweise Nutzungslimits. [8]', pages: [], chapters: [] },
        { text: 'Trinkwasserversorgungssysteme beschränken sich häufig auf eine Ressource (z.B. Grundwasser). Wenn diese ausfällt (z.B. durch Dürre) kann das zu Engpässen führen. [8]', pages: [], chapters: [] },
        { text: 'Wasserknappheit und Nutzungslimits sind kein Problem der Zukunft: In der Wasserkrise von Kapstadt (2015-2018) wurde der Wasserverbrauch aufgrund extremer Dürre und sinkendem Pegel, der für die Trinkwasserversorgung genutzten Talsperre, zeitweise auf 50 Liter pro Person pro Tag begrenzt. [8]', pages: [], chapters: [] },
        { text: 'Durch Dürre und Hitze (z.B. Verdunstung) können Schadstoffe in Oberflächengewässern nicht richtig verdünnt werden, wodurch die Wasserqualität sinkt. [9]', pages: [], chapters: [] },
        { text: 'Mit dem Klimawandel entsteht eine schwer beherrschbare Krise der Wasserverfügbarkeit, die erhebliche Folgen für das Ökosystem und den Menschen mit sich bringt. [9]', pages: [], chapters: [] },
        { text: 'Ohne Maßnahmen könnte sich die jährlich in die Umwelt gelangende Kuststoffmenge bis 2060 weltweit auf etwa 44 Mio. Tonnen erhöhen, wodurch auch die Belastung durch Mikro- und Nanoplastik erheblich zunehmen würde. Das wiederum hätte negative Auswirkungen auf die Wasserqualität. [10]', pages: [], chapters: [] },
        { text: 'Die Nachfrage nach Wasser wird sich laut UNESCO (2023) jährlich um ca. 1% erhöhen. Im Jahr 2050 wäre das ein Zuwachs von 20-30% [11]', pages: [], chapters: [] },
        { text: 'Durch die globale Erwärmung nehmen die Bodenfeuchte und grünes Wasser (z.B. Regenwasser) ab, was sich auf die gesamte Wasserverfügbarkeit auswirkt. [12]', pages: [], chapters: [] },
        { text: 'Kommt es als Reaktion auf den Klimawandel zu einer steigenden Grundwasserentnahme, könnten durch die Übernutzung Grundwasseranteile auf der ganzen Welt knapp werden. [12]', pages: [], chapters: [] },
        { text: 'Bis Ende des Jahrhunderts kann mit anhaltenden Perioden geringer Grundwasserstände gerechnet werden. [13]', pages: [], chapters: [] },
        { text: 'Auch in Regionen wie Deutschland, in denen das Wasseraufkommen eher hoch ist, führt der Klimawandel zunehmend zu Wasserstress, insbesondere durch heiße, trockene Sommer. [14]', pages: [], chapters: [] },
        { text: 'Grundwasser ist in Deutschland mit fast 70% die wichtigste Trinkwasserquelle. 2019 wurden in Deutschland 62,4% des Trinkwassers aus dem Grundwasser, 12,6% aus See- und Talsperren, 8% aus angereichertem Grundwasser, Uferfiltrat und Quellwasser sowie 1,2% aus Flusswasser gewonnen. [14][15]', pages: [], chapters: [] },
        { text: 'Im Jahr 2019 nutzte die an die Wasserversorgung angeschlossene Bevölkerung etwa 128 Liter pro Person pro Tag. [16]', pages: [], chapters: [] },
        { text: 'Durch den Klimawandel und dadurch häufiger auftretenden Hitzewellen und Dürren, wird es in Deutschland zunehmend zu regionaler Wasserknappheit und Wassernutzungskonflikten kommen. [17]', pages: [], chapters: [] },
        { text: '2022 waren hauptsächlich PrivatverbraucherInnen von Wassernutzungskonflikten betroffen (v.A. durch Entnahmeverbote oder kurzfristige Abhängigkeit von einer Trinkwasser-Ersatzversorgung). [18]', pages: [], chapters: [] },
        { text: 'Dürren werden als "neue Normalität" häufiger und länger auftreten. [19]', pages: [], chapters: [] },
        { text: 'Viele Regionen in Deutschland sind bereits von Wasserknappheit und Wassernutzungskonflikten betroffen. Der Klimawandel und ein steigender Bedarf verschärfen die Situation, insbesondere während Trockenperioden. [19]', pages: [], chapters: [] },
        { text: 'Ein Ansatz zur Erweiterung des Wasserangebots ist die Meerwasserentsalzung, die allerdings Nebeneffekte hat. [20]', pages: [], chapters: [] },
        { text: 'Bei Meerwasserentnahme und Rückführung wird das Wasserökosystem belastet. [21]', pages: [], chapters: [] },
        { text: 'Durch fortschreitenden Klimawandel und Wasserverschmutzung one Schutz- und Regulierungsmaßnahmen ist langfristig mit erheblichen Risiken für die Wasserversorgung der Bevölkerung mit qualitativ geeignetem Wasser zu rechnen. [22]', pages: [], chapters: [] },
        { text: 'In Zukunft wird voraussichtlich mehr Wasser aus Meeren, Böden und anderen Wasseroberflächen verdunsten. Gleichzeitig kann die Atmosphäre immer größere Mengen Wasser aufnehmen. Dadurch geht an vielen Orten weltweit mehr Wasser von der Erdoberfläche verloren. [22]', pages: [], chapters: [] },
        { text: 'Der Verlust von Grundwasser kann Wassermangel verstärken, Grundwasserversalzung verursachen, zum Versiegen von Brunnen beitragen, Ökosysteme die vom Grundwasser abhängen schädigen, das Eindringen von Abwasser ins Grundwasser begünstigen sowie zum Verlust von Vegetation und Biodiversität beitragen. [22]', pages: [], chapters: [] },
        { text: 'Insbesondere Süd- und Mitteleuropa verlieren schnell an Wasserreserven. Die Südhälfte Europas von Spanien bis Deutschland wird immer trockener [23]', pages: [], chapters: [] },
      ],
    },

    {
      title: 'WASSERKNAPPHEIT',
      bullets: [
        { text: 'Wasser ist ein knappes, begehrtes und ungleich verteiltes Gut. [24]', pages: [4, 65, 41], chapters: [1, 5, 8] },
        { text: 'Einkommensstarke Bevölkerungsgruppen im urbanen Raum verbrauchen mehr Wasser als andere Gruppen (Übernutzung). [2]', pages: [4], chapters: [1] },
        { text: 'Der Wasserverbrauchsindes Plus (WEI+) zeigt, wie stark die verfügbaren Wasservorräte genutzt werden. Er macht deutlich, ob in einer Region genug Süßwasser vorhanden ist oder ob bereits Wassermangel droht. Wenn mehr als 20% des verfügbaren Wassers verbraucht werden, gilt das Gebiet bereits als belastet. Steigt der Wert über 40%, wird so viel Wasser genutzt, dass dies auf Dauer problematisch und möglicherweise nicht mehr umweltverträglich ist. [2]', pages: [5], chapters: [1] },
        { text: 'Etwa 2,2 Mrd. Menschen haben keinen sicheren Zugang zu Trinkwasser, insbesondere Menschen mit geringerem Einkommen (UNESCO, 2024). [6]', pages: [13], chapters: [1] },
        { text: 'Insbesondere in ländlichen Gebieten ist die Versorgungslage eine Herausforderung. [6]', pages: [13], chapters: [1] },
        { text: 'In einigen Regionen Deutschlands muss die bewässerte Fläche in Zukunft limitiert werden um in der zweiten Hälfte des 21. Jahrunderts die öffentliche Wasserversorgung auch bei Grundwasserknappheit sicherzustellen. [25]', pages: [27], chapters: [3] },
        { text: 'Zu diesen Regionen zählen unter anderem Regionen im Oberrheingraben, im westlichen Nordrhein-Westfalen, im südöstlichen Niedersachsen, im mitteldeutschen Trockengebiet sowie Brandenburg und Mecklemburg-Vorpommern. [25]', pages: [27], chapters: [3] },
        { text: 'Durch sinkende Grundwasserspiegel und Niedrigwasserperioden über einen längeren Zeitraum können Nutzungskonflikte zwischen Haushalten, Industrie, Landwirtschaft und Wasserökosystemen enstehen oder verschärft werden. [26]', pages: [27], chapters: [3] },
        { text: 'Simulationen zeigen eine starke Zunahme extremer Dürren ab den 2030er Jahren bis zwischen 2081 und 2100 kein Jahr in Deutschland nicht als extrem trocken eingestuft wird. [27]', pages: [36], chapters: [4] },
        { text: 'Fehlender Zugang zu sauberem Trinkwasser wirkt sich bei älteren Menschen häufig schneller lebensverkürzend aus, als bei jungen Menschen. [28]', pages: [38, 39], chapters: [4, 5] },
        { text: 'Wasserknappheit in Kapstadt 2015: Der Wasserverbrauch wurde vorübergehend auf 50 Liter pro Person pro Tag begrenzt. [8]', pages: [41, 65], chapters: [5, 8] },
        { text: 'Eine mangelhafte Wasserversorgung beeinträchtigt neben der Vitalität und Leistung eines Menschen auch die Leistung der Gesellschaft, was zu wirtschaftlichen und gesellschaftspolitischen Konzequenzen führen kann. [5]', pages: [44, 72, 73], chapters: [5, 9] },
        { text: 'Dehydration ist die Konsequenz von Wassermangel und wenn der Körper nicht mehr in der Lage ist die übermäßige Hitze zu auszugelichen. [29]', pages: [56], chapters: [7] },
        { text: 'Etwa die Hälfte des Jahres leidet rund die Hälfte der globalen Bevölkerung unter Wassermangel. [30]', pages: [65, 56, 41], chapters: [8, 5, 7] },
        { text: 'Durch Hitzewellen kommt es zu höherem maximalem Wasserverbrauch pro Tag, wofür die Kapazität von Aufbereitungsanlagen und Verteilungsnetze nicht ausgelegt sind. Daher kommt es zu Nutzungslimits. [8]', pages: [65, 41], chapters: [8, 5] },
        { text: '"Wasser ist der Blutkreislauf der Biosphäre" (Ripl., 2003). [30]', pages: [72, 73], chapters: [9] },
        { text: 'Klimaextreme werden häufiger, darunter auch das Auftreten von Starkregenereignissen. [31]', pages: [72, 73], chapters: [1, 5, 8] },
        { text: 'Extremereignisse wie Hitzewellen, Dürren oder Starkregen werden global betrachtet häufiger, heftiger, treten schneller auf und in kürzeren Zeiträumen. [32]', pages: [72, 73], chapters: [9] },
        { text: 'Starkregenereignisse werden häufiger und intensiver, besonders in Nordamerika, Europa und Asien. [32]', pages: [72, 73], chapters: [9] },
        { text: 'Starkregen und Hochwasser sind keine Jahrhundertereignisse mehr sondern Teil der neuen Realität. [33]', pages: [72, 73], chapters: [9] },
        { text: '. [30]', pages: [72, 73], chapters: [9] },

      ],
    },
    {
      title: 'HITZE',
      bullets: [
        { text: '. [2]', pages: [30, 31], chapters: [2] },
        { text: '. [2]', pages: [36], chapters: [2] },
        { text: '. [3]', pages: [40, 41], chapters: [3] },
        { text: '. [3]', pages: [55, 56], chapters: [3] },
      ],
    },
    {
      title: 'NATUR & BODEN',
      bullets: [
        { text: '. [1]', pages: [60], chapters: [3] },
        { text: '. [3]', pages: [75, 76], chapters: [4] },
        { text: '. [2]', pages: [90], chapters: [4] },
      ],
    },
    {
      title: 'URBANE ENTWICKLUNG',
      bullets: [
        { text: '. [1]', pages: [60], chapters: [3] },
        { text: '. [3]', pages: [75, 76], chapters: [4] },
        { text: '. [2]', pages: [90], chapters: [4] },
      ],
    },
    {
      title: 'SOZIALE ISOLATION',
      bullets: [
        { text: '. [1]', pages: [60], chapters: [3] },
        { text: '. [3]', pages: [75, 76], chapters: [4] },
        { text: '. [2]', pages: [90], chapters: [4] },
      ],
    },
    {
      title: 'EXTREMWETTER',
      bullets: [
        { text: '. [1]', pages: [60], chapters: [3] },
        { text: '. [3]', pages: [75, 76], chapters: [4] },
        { text: '. [2]', pages: [90], chapters: [4] },
      ],
    },
  ],
  sources: [
    { id: 0, text: 'BUND, 2025' },
    { id: 1, text: 'Amparo-Salcedo et al., 2025, S. 5' },
    { id: 2, text: 'European Environment Agency, 2025' },
    { id: 3, text: 'European Commission, 2026' },
    { id: 4, text: 'WBGU - Wissenschaftlicher Beirat der Bundesregierung Globale Umweltveränderungen, 2024, S.1' },
    { id: 5, text: 'WBGU - Wissenschaftlicher Beirat der Bundesregierung Globale Umweltveränderungen, 2024, S.5' },
    { id: 6, text: 'WBGU - Wissenschaftlicher Beirat der Bundesregierung Globale Umweltveränderungen, 2024, S.29' },
    { id: 7, text: 'WBGU - Wissenschaftlicher Beirat der Bundesregierung Globale Umweltveränderungen, 2024, S.87' },
    { id: 8, text: 'WBGU - Wissenschaftlicher Beirat der Bundesregierung Globale Umweltveränderungen, 2024, S.75' },
    { id: 9, text: 'WBGU - Wissenschaftlicher Beirat der Bundesregierung Globale Umweltveränderungen, 2024, S.78' },
    { id: 10, text: 'WBGU - Wissenschaftlicher Beirat der Bundesregierung Globale Umweltveränderungen, 2024, S.79' },
    { id: 11, text: 'WBGU - Wissenschaftlicher Beirat der Bundesregierung Globale Umweltveränderungen, 2024, S.80' },
    { id: 12, text: 'WBGU - Wissenschaftlicher Beirat der Bundesregierung Globale Umweltveränderungen, 2024, S.4' },
    { id: 13, text: 'Wunsch et al., 2022, S.1' },
    { id: 14, text: 'Wunsch et al., 2022, S.2' },
    { id: 15, text: 'Flörke et al., 2024, S.73' },
    { id: 16, text: 'Flörke et al., 2024, S.83' },
    { id: 17, text: 'Flörke et al., 2024, S.156' },
    { id: 18, text: 'Flörke et al., 2024, S.158' },
    { id: 19, text: 'Flörke et al., 2024, S.290' },
    { id: 20, text: 'WBGU - Wissenschaftlicher Beirat der Bundesregierung Globale Umweltveränderungen, 2024, S.38' },
    { id: 21, text: 'WBGU - Wissenschaftlicher Beirat der Bundesregierung Globale Umweltveränderungen, 2024, S.40' },
    { id: 22, text: 'WBGU - Wissenschaftlicher Beirat der Bundesregierung Globale Umweltveränderungen, 2024, S.66-69' },
    { id: 23, text: 'Rezaee, 2025' },

    //Sources for Wasserknappheit 
    { id: 24, text: 'WBGU - Wissenschaftlicher Beirat der Bundesregierung Globale Umweltveränderungen, 2024, S.86-87' },
    { id: 25, text: 'Flörke et al., 2024, S.25' },
    { id: 26, text: 'Flörke et al., 2024, S.44' },
    { id: 27, text: 'Flörke et al., 2024, S.94' },
    { id: 28, text: 'WBGU - Wissenschaftlicher Beirat der Bundesregierung Globale Umweltveränderungen, 2024, S.42' },
    { id: 29, text: 'Landeshauptstadt Stuttgart: Gesundheitsamt und Amt für Umweltschutz, 2025, S.15' },
    { id: 30, text: 'WBGU - Wissenschaftlicher Beirat der Bundesregierung Globale Umweltveränderungen, 2024, S.30' },
    { id: 31, text: 'Flörke et al., 2024, S.296' },
    { id: 32, text: 'WBGU - Wissenschaftlicher Beirat der Bundesregierung Globale Umweltveränderungen, 2024, S.36' },
    { id: 33, text: 'Bundesministerium für Umwelt, Klimaschutz, Naturschutz und nukleare Sicherheit, 2025' },

  ],
};

export default content;
